### ISSUE TITLE
My Twilio Video doesn't have the "Room name" 

### ISSUE THREAD

**Issue by GabrielRamaldes** [twilio/video-quickstart-js#100]
![image](https://user-images.githubusercontent.com/56983194/71216857-8632b700-229a-11ea-8597-e43e47d040d4.png)

When i type "npm start" at the CMD and enter http://localhost:3000/quickstart/, everything seems to bee working but doesn't have the "Room name" part, like the example on README.

Someone knows how to solve this problem?

**Comment by manjeshbhargav** [comment]
Hi @GabrielRamaldes ,

Sorry for the late response. What do you mean by _it doesn't have the "Room name" part_? And is it happening before or after joining the Room?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GabrielRamaldes** [comment]
@manjeshbhargav when i enter Twilio Video Quickstart page, it doesn't have the "Room Name" part like the image on README.md.
![image](https://user-images.githubusercontent.com/56983194/73073989-54170500-3e97-11ea-8c2d-76a13f8cfd57.png)

**Comment by manjeshbhargav** [comment]
@GabrielRamaldes ,

That's weird. Can yo share what you see in the JavaScript console with me? Maybe there is some issue when trying to join a Room.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GabrielRamaldes** [comment]
@manjeshbhargav but that is the problem, i can't join any room in Twilio Video because this option does not appears to me :(

**Comment by manjeshbhargav** [comment]
@GabrielRamaldes ,

Maybe there is a problem loading the webpage. Your screenshot seems to indicate that there was some error and the page did not load fully. Can you share your JavaScript console logs?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GabrielRamaldes** [comment]
![image](https://user-images.githubusercontent.com/56983194/73214972-f5b98300-4131-11ea-8e57-3309bd56f49e.png)

Here it is. Sorry for the delay.

**Comment by manjeshbhargav** [comment]
@GabrielRamaldes ,

It looks like the `/token` endpoint is not reachable. Please make sure that the token server is running. That should unblock you from running the app. I'll close this issue, since the solution is fairly straightforward. Feel free to post your response here after you get the token server running. You can do that either by running `npm start` or `node server` from the project root.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GabrielRamaldes** [comment]
@manjeshbhargav but that was exactly what i did, run "npm start" in the project root, in CMD.
