### ISSUE TITLE
track.attach is not a function when trying to display participant's track

### ISSUE THREAD

**Issue by psgganesh** [twilio/video-quickstart-js#101]
Trying to display participant's tracks, but always runs into tracks.attach is not a function error, even the div id="remoteTrack"  is present on the DOM

```js
      const remoteDiv = document.getElementById('remoteTrack');
      
      // 1. Handle any Participants already present in the `participants` Map.
      room.participants.forEach(participant => {

        // 3. Handle any Tracks already present in a Participant's `tracks` Map.
        participant.tracks.forEach(track => {
          remoteDiv.appendChild(track.attach());
        });

        // 4. Handle any Tracks added after the fact via the "trackAdded" event.
        participant.on('trackAdded', track => {
          remoteDiv.appendChild(track.attach());
        });
      });

      // 2. Handle any Participant who may connect 
      // via the "participantConnected" event.
      room.on('participantConnected', participant => {

        // 3. Handle any Tracks already present in a Participant's `tracks` Map.
        participant.tracks.forEach(track => {
          remoteDiv.appendChild(track.attach());
        });

        // 4. Handle any Tracks added after the fact via the "trackAdded" event.
        participant.on('trackAdded', track => {
          remoteDiv.appendChild(track.attach());
        });
      });
```

**Comment by psgganesh** [comment]
My participant's track has both audio and video tracks when it goes through `tracks.forEach`

**Comment by psgganesh** [comment]
`track.attach()` only works on twilio-video 1.x.x versions, does not work for 2.x.x versions, unfortunately this is not documented anywhere / not reflected on any of twilio's blog posts.

I had to chang my twilio video versions to get them working.

**Comment by manjeshbhargav** [comment]
@psgganesh ,

Thanks for writing in with your issue. `track.attach()` indeed works with the 2.x.x version. The reason you got that error is because in 2.x.x, `RemoteParticipant.tracks` now contains [TrackPublications](https://www.twilio.com/docs/video/migrating-1x-2x#trackpublication) instead of Tracks. Also, you can refer to our [2.x quickstart code](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/index.js) to see how to cycle through the RemoteParticipant's `tracks` collection.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by germanolsd** [comment]
https://www.twilio.com/docs/video/migrating-1x-2x#trackpublication
this link is incredibly unhelpful

**Comment by JuanGaray93** [comment]
Why are the default docs about the 1.x versions? I'm trying to go through it and only found out I was on the wrong version because of this issue.
