### ISSUE TITLE
How screen sharing feature is work in safari ?

### ISSUE THREAD

**Issue by divya-kanak** [twilio/video-quickstart-js#105]
I am using https://www.twilio.com/docs/video/migrating-1x-2x for the app.

Screen sharing is working fine in chrome and firefox but that is not working in safari.

So, anyone can help with that, How screen sharing feature is working in safari?

**Comment by manjeshbhargav** [comment]
Hi @divya-kanak ,

Thanks for writing in with your question. Screen sharing will work in Safari 12.2+. Please check your Safari version. Also, please refer to the [Screen Share Guide](https://www.twilio.com/docs/video/screen-capture-chrome#chrome-72-firefox-66-safari-122-use-getdisplaymedia).

Thanks,

Manjesh Malavalli
JSDK Team
