### ISSUE TITLE
Video streaming is not working in Safari OS X 13.0.4

### ISSUE THREAD

**Issue by divya-kanak** [twilio/video-quickstart-js#107]
I am doing testing of the app in Safari OS X 13.0.4 for live video sharing. I am using Twilio's API for that.
But video the streaming having as an issue. please check below link : 
https://prnt.sc/qvgfxu

I have also trying to testing using third party site this https://www.webrtc-experiment.com/getDisplayMedia/

But in this case, also the issue is the same, please check below : 
https://prnt.sc/qvgfjq

**Comment by manjeshbhargav** [comment]
Hi @divya-kanak ,

Sorry for the delayed response. Just for future reference, if you have any questions or concerns with the Video JS SDK, please open an issue in the [SDK repo](https://github.com/twilio/twilio-video.js/issues), which is more closely monitored than the issues here.

Can you re-run your test with `logLevel: 'debug'` in ConnectOptions and share the browser logs? That would help us in debugging your issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @divya-kanak ,

I'm going to close this issue. Please open an issue in the [SDK repo] if you run into any other problems.

Thanks,

Manjesh Malavalli
JSDK Team
