### ISSUE TITLE
Could not connect to Twilio: Signaling connection error (chrome (v - 67) and chrome (v- 79))

### ISSUE THREAD

**Issue by divya-kanak** [twilio/video-quickstart-js#108]
Hello folks, 

I am trying to make the connection between chrome (v - 67) and chrome (v- 79), at the time got the error like:

` WebSocket connection to 'wss://global.vss.twilio.com/signaling' failed: Error in connection establishment: net:: ERR_SOCKS_CONNECTION_FAILED`

I have attached the video link here. please check out and let me help out for this.

Chrome (v-79) : connection is successfully. 
check below url- [https://drive.google.com/file/d/1aVsRhDEmp7q1atAwMcbh9L_bPv-iiqNA/view](https://drive.google.com/file/d/1aVsRhDEmp7q1atAwMcbh9L_bPv-iiqNA/view)

Chrome(v-67): Could not connect to Twilio: Signaling connection error
check URL: [https://drive.google.com/file/d/1TbGaJ_aSyfswTGOXA-8Sw1u_s_skBH-C/view](https://drive.google.com/file/d/1TbGaJ_aSyfswTGOXA-8Sw1u_s_skBH-C/view)

I have added below option in `connectOptions` 

`const connectOptions = {
  _useTwilioConnection: true
};`

But I have faced the same issue. I have created an Http tunnel. So, If you want to check this feature using my end. 
please hit this link: [https://b256e195.ngrok.io ](https://b256e195.ngrok.io ) 

 - [x] Browser(s): Chrome(v-79), Chrome(v-67) (not working), Chrome(v-75) (not working)
 - [x] Operating System: window 10
 - [x] twilio-video.js: we have migrate from 1.x to 2.x
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular js

**Comment by manjeshbhargav** [comment]
Hi @divya-kanak ,

Sorry for the delayed response. Just for future reference, if you have any questions or concerns with the Video JS SDK, please open an issue in the [SDK repo](https://github.com/twilio/twilio-video.js/issues), which is more closely monitored than the issues here.

Can you re-run your test with logLevel: 'debug' in ConnectOptions and share the browser logs? That would help us in debugging your issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @divya-kanak ,

Since there hasn't been response from you, I'm closing this issue. Please feel free to reopen if you have more information.

Thanks,

Manjesh Malavalli
JSDK Team
