### ISSUE TITLE
ICE connection state is "disconnected"

### ISSUE THREAD

**Issue by Awais-cb** [twilio/video-quickstart-js#113]
stream does not work in the most cases

[PeerConnectionV2 #2: 680a99b6-ae2d-4884-9d8d-8660a166273c]: ICE connection state is "disconnected"

getting this in console with debug mode on.any idea about this any help would be really appreciated

**Comment by manjeshbhargav** [comment]
Closing as duplicate of https://github.com/twilio/twilio-video.js/issues/945.
