### ISSUE TITLE
Video streaming is not working from Safari IOS to any device. black screen appears

### ISSUE THREAD

**Issue by ashishgarg624** [twilio/video-quickstart-js#116]
Hi, 

iPhone safari version: 11.2.5
Chrome version: Checking for updates Version 80.0.3987.163 (Official Build) (64-bit)
The connection is a peer to peer.

If I can give you an overview it's like -
Video is coming on iPhone from mac safari, Chrome, window laptop
Video is coming on Android Phone from mac safari, Chrome, window laptop
Video is coming on mac safari, Chrome, window laptop from Android Phone

Video is NOT COMING on mac safari, Chrome, window laptop from iPhone

Please let me know if you can help. Thanks in advance.

**Comment by manjeshbhargav** [comment]
Hi @ashishgarg624 ,

Thanks for writing in with your issue. From what you have described, it looks like you are creating two camera tracks, once when you call `connect(token, { video: { ... } })` and once when you call `createLocalVideoTrack()` to show your camera preview. Let me know if you are indeed doing this.

If this is the case, then on mobile browsers you are only allowed to have one camera track at a time. So, what you can do is re-use the camera track from `connect()` to show your camera preview:

```js
const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
divContainer.appendChild(localVideoTrack.attach());
```

Please let me know if this works for you. Also, please refer to this [guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices) for best practices and recommendations for mobile browsers.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ashishgarg624** [comment]
It works!!. You save my day.

Thanks.

**Comment by nawalnew** [comment]
Hey I have the same Problem I think but everything I try, dont get the Phone Video to work -.- 
I dont seem to add the Video twice I think. 
But could someone please Provide me some help please?

Everything works fine, except the black screen if I join on mobile.

Ive shrinked down the code just to the connecting part.

```javascript
getTracks(participant) {
       return Array.from(participant.tracks.values()).filter(function (publication) {
          return publication.track;
       }).map(function (publication) {
          return publication.track;
       });
    },

    createChat(room_name) {
      const VueThis = this;

      this.getAccessToken().then( (data) => {
          VueThis.roomName = null;
          const token = data.data;

          let connectOptions = {
              name: room_name,
              audio: true,
            video: { name: 'camera', width: { min: 640, ideal: 1280 }, height: { min: 480, ideal: 720 } },
            preferredVideoCodecs: ['H264']
          };

          Twilio.connect(token, connectOptions).then(  (room) => {

            // if local preview is not active, create it
              if(!VueThis.localTrack) {
                  createLocalVideoTrack().then(track => {
                    let localMediaContainer = document.getElementById('localTrack');

                    localMediaContainer.appendChild(track.attach());
                    VueThis.localTrack = true;
                  });
              }

              this.localIdentity = room.localParticipant;

              $nuxt.$emit('pconnect', {"success":true});

              // set active room
              VueThis.activeRoom = room;
              VueThis.roomName = room_name;

            room.participants.forEach(participantConnected);
            room.on('participantConnected', participantConnected);

            room.on('participantDisconnected', participantDisconnected);
            room.once('disconnected', error => room.participants.forEach(participantDisconnected));


            room.on('disconnected', room => {

              room.localParticipant.tracks.forEach(publication => {

                publication.track.stop();
                publication.unpublish();
                const attachedElements = publication.track.detach();
                attachedElements.forEach(element => element.remove());
              });
            });


            function participantConnected(participant) {

              const div = document.createElement('div');
              div.id = participant.sid;
              div.innerText = participant.identity;


              participant.on('trackSubscribed', track => trackSubscribed(div, track));
              participant.on('trackUnsubscribed', trackUnsubscribed);

              participant.tracks.forEach(publication => {
                if (publication.isSubscribed) {
                  trackSubscribed(div, publication.track);
                }
              });


              let previewContainer = document.getElementById('remoteTrack');
              previewContainer.append(div);

              }

              function trackSubscribed(div, track) {
                div.appendChild(track.attach());
              }
            

         } , response => {

               $nuxt.$emit('pconnect', {"success":false});
           });
        
      })
   }```

**Comment by manjeshbhargav** [comment]
Hi @nawalnew ,

You are creating two video tracks. One of them is created by the SDK using the constraints you have passed in `ConnectOptions`. The second one is created by you when you call `createLocalVideoTrack()` by you in order to create the preview. Instead of that, you can access the already created LocalVideoTrack as follows:
```js
const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
divContainer.appendChild(localVideoTrack.attach());
```
Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by nawalnew** [comment]
Thank you @manjeshbhargav 
It worked 💯 

I have just a question for the reconnect logic if a loose of a signal (Wifi/Cellular) happens. 

Do you have a hint for implementing it on my code on the right position? 

Would be nice :)

**Comment by manjeshbhargav** [comment]
Hi @nawalnew ,

You can listen to the Room's "reconnecting" and "reconnected" events and update the user interface accordingly:
```js
room.on('reconnecting', () => {
  /* Update UI */
});

room.on('reconnected', () => {
  /* Update UI */
});
```
Thanks,

Manjesh Malavalli
JSDK Team
