### ISSUE TITLE
Video is not showing on android chrome 81.xxx

### ISSUE THREAD

**Issue by superdev961992** [twilio/video-quickstart-js#119]
Whenever I am trying to connect room from android chrome browser the room gets connected and I am able to hear the Audio. But video for remote participant is not visible. In the logs I can see "No supported codecs"

Logs : error":{"code":53404,"message":"No supported codec. Codec video/H264/90000/1,fmtps:[(level-asymmetry-allowed, 1), (packetization-mode, 1), (profile-level-id, 42e01f)] is not supported. Supported codecs: [video/H264/90000/1,fmtps:[(level-asymmetry-allowed, 1), (packetization-mode, 1), (profile-level-id, 42e015)]]"}}]},"published":{"revision":1,"tracks":[]}},"type":"msg"}

**Comment by manjeshbhargav** [comment]
Hi @superdev961992 ,

We already have an open issue for this and a [potential workaround](https://github.com/twilio/twilio-video.js/issues/966#issuecomment-619212184) while we apply it to our SDK and possibly our media server. I'm closing this issue as a duplicate.

Thanks,

Manjesh Malavalli
JSDK Team
