### ISSUE TITLE
Need to customize it by unable/disable the audio

### ISSUE THREAD

**Issue by bhattaxay** [twilio/video-quickstart-js#121]
Hi there,

I want to know that how do i use the helper of your sdk like unable/disable the audio/video.

**Comment by bhattaxay** [comment]
Hii there,

I have tried with given helper.js for mute/unmute audio and enable/disable video but it's not working while integrate it in quickstart. Can you pls let me know which is the proper method to mute/unmute audio and enable/disable video.

**Comment by irshadhub** [comment]
Hi Akshay (bhattaxay),

You have to modify **joinroom.js** file to add Audio mute/unmute and Video Stop/Start Buttons.
Search **setupParticipantContainer** function in joinroom.js and replace it with below given complete code.


    /* To Mute and Un-Mute the Audio */
    function muteLocalParticipant( audioBtn ) {
  
        const mute = !audioBtn.hasClass('muted');
        const participantSID = audioBtn.parent().data('sid');
        
        if (mute) {
        muteYourAudio(room);
        audioBtn.addClass('muted');
        audioBtn.html('<span class="audio-off"></span>');
        } else {
        unmuteYourAudio(room);
        audioBtn.removeClass('muted');
        audioBtn.html('<span class="audio-on"></span>');
        }
    } // End :: muteLocalParticipant()
  
  
  
    /*  To Stop and Start the Video */
    function videoLocalParticipant( videoBtn ) {
    
        const mute = !videoBtn.hasClass('muted');
        const participantSID = videoBtn.parent().data('sid');
    
        if (mute) {
        muteYourVideo(room);
        videoBtn.addClass('muted');
        videoBtn.html('<span class="video-off"></span>');
        }
        else {
        unmuteYourVideo(room);
        videoBtn.removeClass('muted');
        videoBtn.html('<span class="video-on"></span>');
        }
    
    } // End :: videoLocalParticipant()

    /* navigator.mediaDevices.enumerateDevices() */
    function setupAudioVideocontrols(room, userName, sid) {

        const $controls = $(`<div id="userControls-${sid}" class="bottom-right" data-sid="${sid}"> </div>`);
        const audioBtn = $(`<button id="muteAudioBtn-${sid}" class="btn btn-light btn-sm"><span class="audio-disable"></span></button>`); // Mute & UnMute
        const videoBtn = $(`<button id="muteVideoBtn-${sid}" class="btn btn-light btn-sm"><span class="video-disable"></span></button>`); // Video On Off
        const closeBtn = $(`<button id="closeBtn-${sid}" class="btn btn-light btn-sm"><i class="fa fa-times endVideo"></i></button>`); // Close others
    
        audioBtn.on("click", function () {
        muteLocalParticipant( $(this) );
        });

        videoBtn.on("click", function () {
        videoLocalParticipant( $(this) );
        });
    
        $controls.append(audioBtn);
        $controls.append(videoBtn);
    
        return $controls
    
    } // End :: setupAudioVideocontrols{}
    
    /**
     * Set up the Participant's media container.
     * @param participant - the Participant whose media container is to be set up
     * @param room - the Room that the Participant joined
     */
    function setupParticipantContainer(participant, room) {
        const { identity, sid } = participant;
    
        // Add a container for the Participant's media.
        const $container = $(`<div class="participant item" data-identity="${identity}" id="${sid}">
        <audio autoplay ${participant === room.localParticipant ? 'muted' : ''} style="opacity: 0"></audio>
        <video autoplay muted playsinline style="opacity: 0"></video>
        </div>`);
    
        // Toggle the pinning of the active Participant's video.
        $container.on('click', () => {
        if (activeParticipant === participant && isActiveParticipantPinned) {
            // Unpin the RemoteParticipant and update the current active Participant.
            setVideoPriority(participant, null);
            isActiveParticipantPinned = false;
            setCurrentActiveParticipant(room);
        } else {
            // Pin the RemoteParticipant as the active Participant.
            if (isActiveParticipantPinned) {
            setVideoPriority(activeParticipant, null);
            }
            setVideoPriority(participant, 'high');
            isActiveParticipantPinned = true;
            setActiveParticipant(participant);
        }
        });
    
        
        var videoDiv = $(`<div class="video-group" id="avbtn-${sid}"></div>`);
        videoDiv.append($container);
        
        const $controls = setupAudioVideocontrols(room, userName, sid);
        videoDiv.append($controls); // Buttons on Video boxes
    
        // Add the Participant's container to the DOM.
        $participants.append(videoDiv);
    
    } // End :: setupParticipantContainer()

**Comment by indigoicon** [comment]
Hi Irshad hub,

can you help me , i have integrated this quick start video on my web  , andriod and iphone
but for some reason mute for all participants and local mute is not working , i also want to integrate screen share
can you help me out ? I can pay you if you want.

**Comment by manjeshbhargav** [comment]
Hi @indigoicon ,

You can mute/unmute your local audio and video by calling `disable()` and `enable()` on your LocalAudioTrack and LocalVideoTrack. Regarding Screen Share, please see this [guide](https://www.twilio.com/docs/video/screen-capture-chrome).

Thanks,

Manjesh Malavalli
JSDK Team
