### ISSUE TITLE
Error: keySid is required

### ISSUE THREAD

**Issue by aravindkumar01** [twilio/video-quickstart-js#126]
I have a trial account. I am trying to run the application but it shows error. But I will follow
the given steps are given in the https://github.com/twilio/video-quickstart-js.
![image](https://user-images.githubusercontent.com/31234837/82143192-af626e00-985f-11ea-971f-8509815e234e.png)

Please, anyone, help me!

**Comment by manjeshbhargav** [comment]
Hi @aravindkumar01 ,

Thanks for writing in with your issue. The error says that you have not provided your API Key. Did you follow the [instructions](https://github.com/twilio/video-quickstart-js#setup-requirements) to create your API Key and Secret and store it in a `.env` file in the project root folder?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @aravindkumar01 ,

Since I haven't heard back from you in a while, I will close this issue. Please re-open if necessary.

Thanks,

Manjesh Malavalli
JSDK Team
