### ISSUE TITLE
Error while switching camera to back camera in mobile (Samsung Android and other devices also)

### ISSUE THREAD

**Issue by avaiyahardik** [twilio/video-quickstart-js#127]
Hi,

Thank you for this library.
We are trying to integrate in one of the project.
Observed below issue with this demo.

While opening the URL in mobile browser, it asks for audio and video channel to use.
It shows 2 options for mobile device camera(front and back camera).
By default it shows front camera as selected but when I try to switch to the back camera in drop down (in popup), it did not change the view and showed below error in console.

 **index.js:29080 Uncaught (in promise) DOMException: Could not start video source**

Appreciate your support.

Attached screenshot
![Twilio video change error](https://user-images.githubusercontent.com/7576413/82228093-4ace0e80-9946-11ea-8dde-9995f0486632.png)

**Comment by manjeshbhargav** [comment]
Hi @avaiyahardik ,

Are you using this QuickStart example as is, or have you made any changes to it? If so, please share the changes you made and I will investigate further. One more thing, the SDK does not support Samsung browser. It supports only Chrome and Firefox on Android.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by avaiyahardik** [comment]
Hi Manjesh,

I am using this library as it is without any change and I am using Android Chrome browser only. It is not specific to Samsung, I have seen the same issue in other devices also.

Thanks
Hardik

**Comment by irshadhub** [comment]
I am also facing the same issue on my mobile [ Moto C Plus and Moto G4 Plus].

**Comment by avaiyahardik** [comment]
Any update on this issue? We need to decide if we should go further with Twilio or take the other path.

**Comment by manjeshbhargav** [comment]
Hi @avaiyahardik @irshadhub ,

This error occurs when another app has taken over the camera. In such cases, you should recommend to users that they should close all other apps and restart the browser.

Our [Best Practices Guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#media-errors) gives you more information on how to handle these errors. Please take a look and let me know if it helps.

Thanks,

Manjesh Malavalli
JSDK Team
