### ISSUE TITLE
How to share-screen with other participants?

### ISSUE THREAD

**Issue by irshadhub** [twilio/video-quickstart-js#128]
I am using this library on my project. I was trying to use the **screenshare** example with ongoing Video Quickstart participants. 

Could you please tell me how we can do this?

Because whenever I am clicking on the ShareScreen button it is showing the shared screen on my browser only and my video is visible on other participant screens. I have 2 video tags on my screen one for Video Chat and another one for Share screen.

Using all this, I am not able to share my screen with other participants with ongoing video chat.

Thanks for this awesome library.

**Comment by irshadhub** [comment]
I found one fix for my problem. I am stopping streaming video and starting screen share streaming using **switchPublishedTracks()** function.

    /**
     * Replace the existing LocalAudioTrack or LocalVideoTrack with
     * a new one in the Room.
     * @param {Room} room - The Room you have joined
     * @param {LocalAudioTrack|LocalVideoTrack} track - The LocalTrack you want to switch to
     * @returns {void}
     */
    function switchPublishedTracks(room, track) {
      room.localParticipant.tracks.forEach(function(trackPublication) {
        if (trackPublication.kind === track.kind) {
          trackPublication.track.stop();
          room.localParticipant.unpublishTrack(trackPublication.track);
        }
      });
      room.localParticipant.publishTrack(track);
    }

    /* share Screen will use this function to toggle the button */
    function toggleButtons() {

      $captureScreen.style.display = $captureScreen.style.display === 'none' ? '' : 'none';
      $stopScreenCapture.style.display = $stopScreenCapture.style.display === 'none' ? '' : 'none';
      $screenPreview.style.display  = $screenPreview.style.display === 'none' ? '' : 'none';

      if( $mainVideo.css('display') == 'none' ) {
        $mainVideo.show();
      } else {
        $mainVideo.hide();
      }

    }

    /**
     * To Share Screen view
     */
    async function shareScreen() {

      // Hide the "Stop Capture Screen" button.
      $screenPreview.style.display = 'none';
      $stopScreenCapture.style.display = 'none';

      // The LocalVideoTrack for your screen.
      let screenTrack;

      $captureScreen.onclick = async function() {

        try {
          // Create and preview your local screen.
          screenTrack = await createScreenTrack(720, 1280);
          screenTrack.attach( $screenPreview );

          switchPublishedTracks( room, screenTrack );

          // Show the "Capture Screen" button after screen capture stops.
          screenTrack.on('stopped', function() {
            
            toggleButtons();
            
            //  we are triggering event of joinroom.js To Start publishing Video with Same connectOptions
            document.dispatchEvent( new Event( "videoRePublish" ) );
            // applyVideoInputDeviceSelection( localStorage.videoDeviceId, $mainVideo, room); // Load setting Video 
          
          });
          
          // Show the "Stop Capture Screen" button.
          toggleButtons();

        } catch (e) {
          alert(e.message);
        }
      };

      $stopScreenCapture.onclick = function() {
        // Stop capturing your screen.
        screenTrack.stop();
      }

    } // End :: shareScreen()

**Comment by likhit-vivek** [comment]
@irshadhub Can you pls share the code for createScreenTrack(720, 1280) function also?

**Comment by irshadhub** [comment]
Hi Team,

Thanks for your reply. Actually I am able to share screen by using switchPublishedTracks() function.

But I want to share my Camera Video and Screen both on Participants page like we do in Zoom.
And  one more thing we are not able to share screen from Mobile phone, it is showing Invalid State alert message.

Could you please tell me how we can achieve it.

My Code is given below :


  1.  Index.js calling  createScreenTrack() function



/* ################################################# */
/* #####          To Share Screen view         ##### */
/* ################################################# */

/* Share Screen include file and declare Variables :: START */
const createScreenTrack = require('./screenshare');
const $captureScreen = document.querySelector('span#capturescreen');
const $screenPreview = document.querySelector('video#screenpreview');
const $stopScreenCapture = document.querySelector('span#stopscreencapture');
/* END :: Share Screen Variables & File declaration */

/**
 * Replace the existing LocalAudioTrack or LocalVideoTrack with
 * a new one in the Room.
 * @param {Room} room - The Room you have joined
 * @param {LocalAudioTrack|LocalVideoTrack} track - The LocalTrack you want to switch to
 * @returns {void}
 */
function switchPublishedTracks(room, track) {
  room.localParticipant.tracks.forEach(function(trackPublication) {
    if (trackPublication.kind === track.kind) {
      trackPublication.track.stop();
      room.localParticipant.unpublishTrack(trackPublication.track);
    }
  });
  room.localParticipant.publishTrack(track);
}

/* share Screen will use this function to toggle the button */
function toggleButtons() {

  $captureScreen.style.display = $captureScreen.style.display === 'none' ? '' : 'none';
  $stopScreenCapture.style.display = $stopScreenCapture.style.display === 'none' ? '' : 'none';
  $screenPreview.style.display  = $screenPreview.style.display === 'none' ? '' : 'none';
}

/**
 * To Share Screen view
 */
async function shareScreen() {

  // Hide the "Stop Capture Screen" button.
  $screenPreview.style.display = 'none';
  $stopScreenCapture.style.display = 'none';

  // The LocalVideoTrack for your screen.
  let screenTrack;

  $captureScreen.onclick = async function() {

    try {
      // Create and preview your local screen.
      screenTrack = await createScreenTrack(720, 1280);
      screenTrack.attach( $screenPreview );

      switchPublishedTracks( room, screenTrack );

      // Show the "Capture Screen" button after screen capture stops.
      screenTrack.on('stopped', function() {

        toggleButtons(); // if Stooped Toggle

        //  we are triggering event of joinroom.js To Start publishing Video with Same connectOptions
        document.dispatchEvent( new Event( "videoRePublish" ) );
        // applyVideoInputDeviceSelection( localStorage.videoDeviceId, $mainVideo, room); // Load setting Video

      });

      // Show the "Stop Capture Screen" button.
      toggleButtons();

    } catch (e) {
      alert(e.message);
    }
  };

  $stopScreenCapture.onclick = function() {
    // Stop capturing your screen.
    screenTrack.stop();
  }

} // End :: shareScreen()





  1.  Included screenshare.js file


'use strict';

const Video = require('twilio-video');

/**
 * @Irshad Added this file to implement ScreenShare with Video Chat
 * Create a LocalVideoTrack for your screen. You can then share it
 * with other Participants in the Room.
 * @param {number} height - Desired vertical resolution in pixels
 * @param {number} width - Desired horizontal resolution in pixels
 * @returns {Promise<LocalVideoTrack>}
 */
function createScreenTrack(height, width) {

  if ( typeof navigator === 'undefined' || !navigator.mediaDevices || !navigator.mediaDevices.getDisplayMedia ) {
    return Promise.reject(new Error('getDisplayMedia is not supported'));
  }

  return navigator.mediaDevices.getDisplayMedia({
    video: {
      height: height,
      width: width
    }
  }).then(function(stream) {
    return new Video.LocalVideoTrack(stream.getVideoTracks()[0]);
  });
}

module.exports = createScreenTrack;
// exports.createScreenTrack = createScreenTrack;

**Comment by likhit-vivek** [comment]
@irshadhub Don't use switchPublishedTracks() function. Instead publish the screenTrack normally like this:
`room.localParticipant.publishTrack(screenTrack);`

When catching the trackSubscribed event, check for `track.kind`. Based on kind, attach a video track to a separate div and screen track to a separate div. Then I think you can share both video and screen. Console the track object to check what kinds of tracks are available.
```participant.on('trackSubscribed', track => {
                    console.log(track);
                    if(track.kind == 'video') {
                        videoElement = document.getElementById(participant.identity + 'video');
                        videoElement.innerHTML = '';
                        videoElement.appendChild(track.attach());
                    } else if(track.kind == 'audio') {
                        audioElement = document.getElementById(participant.identity + 'audio');
                        audioElement.innerHTML = '';
                        audioElement.appendChild(track.attach());
                    } else if(_______) { Attach the track to screenShare element }
                });

**Comment by likhit-vivek** [comment]
@irshadhub The above logic maynot work... Try using this https://www.npmjs.com/package/multistreamsmixer

**Comment by anna-vasilko** [comment]
@likhit-vivek @irshadhub Hi!
Our demo application demonstrates best practice for collaboration use case (Zoom like) where both video and screenshare tracks are being published and displayed - https://github.com/twilio/twilio-video-app-react

As per mobile browsers, screen can't be shared from mobile browsers, it's an expected limitation on mobile browsers. It can be done with our native iOS and Android SDKs.

**Comment by anna-vasilko** [comment]
Closing, the example can be seen in the demo app provided above.

**Comment by oscarcornejo** [comment]
Twilio has the worst documentation I have ever had to review and the examples are out of date and not applicable to the real world.

I have the same problem to stop and share my screen with other users in the room.
