### ISSUE TITLE
Record Local Track 

### ISSUE THREAD

**Issue by jinming88** [twilio/video-quickstart-js#130]
Hi.
Thanks for your project.
Is there any way to record local track using Twilio Video API?
And after record, I want to save record file to my website.

**Comment by anna-vasilko** [comment]
Hi @jinming88,
You can use our [Recordings REST API](https://www.twilio.com/docs/video/api/recordings-resource) to record tracks in Group rooms 

In Peer-to-Peer Rooms, you can record media from MediaStreamTracks using the MediaRecorder API as shown in [this example](https://webrtc.github.io/samples/src/content/getusermedia/record/).
Hope this helps!

**Comment by jinming88** [comment]
Great Solution.
Just one question.
Is it saved to cloud store?
How can I get saved link?

**Comment by manjeshbhargav** [comment]
Hi @jinming88 ,

The documentation specified in the previous comment describes how you can access the recordings from our cloud.

Thanks,

Manjesh Malavalli
JSDK Team
