### ISSUE TITLE
Only works on W10 Edge - AWS Ubuntu install

### ISSUE THREAD

**Issue by hrostonics** [twilio/video-quickstart-js#131]
I am trying to take Twilio Video for a test-drive and I followed the installation procedure to the dot. 
I am using a AWS Ubuntu Server 18.04 LTS. I have installed Node js and NPM and set the security group on the virtual network to allow for port 3000. 

When I run the  app, it gives me a friendly "Express server running on *:3000"

When I try to hit http://server:3000 I get a "This Browser is not supported" message. This happens on Chrome, Firefox, Safari, and Edge.

When using http://server/mediadevices:3000, only Edge asks for permission to access camera and microphone.

I have also ran tests with the Twilio React video chat sample, and WebRTC toolkit. WebRTC is able to show the camera feed on Edge. 

It looks like something is missing from my setup. Any ideas?

**Comment by hrostonics** [comment]
After I upgraded the environment to NodeJS v12 LTS, 
MediaDevices displays local video successfully on W10 Edge. 
So does Video Filters, but this fails to show anything on the filtered output. 
Chrome and other browsers continue to fail.

**Comment by manjeshbhargav** [comment]
Hi @hrostonics ,

`getUserMedia` is not supported by most browsers when your app is being served from an insecure context (http). You can use `ngrok` to get a secure url (https) and try it out.

Thanks,

Manjesh Malavalli
JSDK Team
