### ISSUE TITLE
Share screen given in this example if giving invalid state alert in mobile

### ISSUE THREAD

**Issue by avaiyahardik** [twilio/video-quickstart-js#132]
I am using Samsung Galaxy On Next.
Chrome browser
Android OS

While trying to share screen from mobile, it shows Invalid state error in the alert box.
Attached screenshot where it is giving error.
![twili-share-screen-error](https://user-images.githubusercontent.com/7576413/83270137-ad949500-a1e5-11ea-8e59-c641780ebf03.PNG)

**Comment by PikaJoyce** [comment]
Hi @avaiyahardik,

I hope all is well. We have updated the documentation to reflect that screen sharing is currently not supported on mobile browsers. [Link to documentation](https://www.twilio.com/docs/video/screen-capture-chrome#screen-share-not-supported-on-mobile-web-browsers)

I will be closing this issue. If you have any other questions or issues, please feel free to reopen this ticket or create a new one if you encounter further issues!

Thank you,
Joyce
