### ISSUE TITLE
TrackName is not setting on ShareScreen Video Track.

### ISSUE THREAD

**Issue by irshadhub** [twilio/video-quickstart-js#137]
I want to set a track name for screen sharing video track.

In the below code, I mentioned track name as "**screen**" but it is not assigning to track. 

Please help me with this, it very urgent for me to set a track name to identify screen share video track with an ongoing video conference.

```
function createScreenTrack(height, width) {

  if ( typeof navigator === 'undefined' || !navigator.mediaDevices || !navigator.mediaDevices.getDisplayMedia ) {
    return Promise.reject(new Error('getDisplayMedia is not supported'));
  }
  
  return navigator.mediaDevices.getDisplayMedia({
    video: {
      height: height,
      width: width,
      name: 'screen'
    }
  }).then(function(stream) {
    return new Video.LocalVideoTrack(stream.getVideoTracks()[0]);
  });
}
```
Image sample for more understanding:

1) Screenshare track name which needs to set.

![share-screen-track-name2](https://user-images.githubusercontent.com/62047407/84512507-c02ec400-ace5-11ea-8d44-af02b1c1b122.png)

2) Camera View track name for reference.

![share-screen-track-name](https://user-images.githubusercontent.com/62047407/84511868-ca9c8e00-ace4-11ea-9509-ea24f82371c0.png)

**Comment by manjeshbhargav** [comment]
Hi @irshadhub ,

You have to specify the name in the options for the LocalVideoTrack constructor and not in getDisplayMedia:
```js
return navigator.mediaDevices.getDisplayMedia({
    video: {
      height: height,
      width: width
    }
  }).then(function(stream) {
    return new Video.LocalVideoTrack(stream.getVideoTracks()[0], { name: 'screen' });
  });
```

**Comment by irshadhub** [comment]
Thanks Manjesh, it is working perfectly now.
