### ISSUE TITLE
How to select multiple cameras

### ISSUE THREAD

**Issue by puneet18190** [twilio/video-quickstart-js#138]
I need to know if multiple cameras attached to my system then is it possible to select & open multiple cameras at a time when join the room?

**Comment by manjeshbhargav** [comment]
Hi @puneet18190 ,

Please take a look at the [Media Devices](https://github.com/twilio/video-quickstart-js/tree/master/examples/mediadevices/src) example in the quickstart.

Thanks,

Manjesh Malavalli
JSDK Team
