### ISSUE TITLE
Changing audio inputs broken in Firefox

### ISSUE THREAD

**Issue by multiplegeorges** [twilio/video-quickstart-js#139]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).

- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.

- [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

- [x]  am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

I have confirmed that this error also occurs in the Twilio Quickstart JS sample code. Just load up the quickstart and try to change the microphone device in Firefox.

I have a simple audio/video settings component in my React app that allows a user to change their currently enabled devices. Here's the handler for changing audio device selection.

Some context removed below...

```typescript
import {
  createLocalAudioTrack as twilioCreateLocalAudioTrack
} from 'twilio-video'

audioConstraints (deviceId?: string) {
  if (deviceId) {
    return { deviceId: deviceId }
  }
}

async createLocalAudioTrack(audioDeviceId?) {
  let state = store.getState()
  audioDeviceId = audioDeviceId || state.devices.audioDeviceId

  return await twilioCreateLocalAudioTrack(audioConstraints(audioDeviceId))
}

async changeAudio (e) {
  const deviceId = e.target.value

  if (this.props.room.localParticipant) {
    this.props.room.localParticipant.audioTracks.forEach((trackPublication) => {
      trackPublication.track.stop()
      trackPublication.unpublish()
    })

    await createLocalAudioTrack(deviceId)
    await this.props.room.localParticipant.publishTrack(track)
  }
  store.dispatch(setDevices({ audioDeviceId: deviceId }))
}
```

**Expected behavior:**

It works in Chrome, does not work in Firefox.
I expect the new track to be successfully publiished.

**Actual behavior:**

An error is generated and the new track is never published.

```
WARN in [createLocalTracks twilio/twilio-video.js#2]: Call to getUserMedia failed: MediaStreamError { name: "NotReadableError", message: "Concurrent mic process limit.", constraint: "", stack: "" }
uncaught exception: Object
```

**Software versions:**

- [x] Browser(s): Firefox 77.0.1
- [x] Operating System: OSX 10.15.2
- [x] twilio-video.js: 2.5.1
- [x] Third-party libraries (e.g., Angular, React, etc.): React 16.13.1

**Comment by multiplegeorges** [comment]
@manjeshbhargav  Thank you for confirming.

I realized the same thing about the stop behaviour in Firefox. 

For others, here's how I am handling it for now:

```javascript
if (track.isStopped) {
  await this.startUpNewtrack()
} else {
  track.on('stopped', async () => { await this.startUpNewtrack() })
  track.stop()
}
```

**Comment by PikaJoyce** [comment]
Hey @multiplegeorges! 

We're currently in the process of fixing this example. I will update this ticket when it is done! 

Thank you,
Joyce

**Comment by PikaJoyce** [comment]
Hi @multiplegeorges!

Thanks again for reporting this issue. It has been fixed. I'll be closing this issue now. Feel free to respond if you have further issues or questions.

Best,
Joyce
