### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by palash14** [twilio/video-quickstart-js#142]
Hi,

if I run build and then I run with localhost without any port then it said token not found.

Could you please help.

**Comment by manjeshbhargav** [comment]
Hi @palash14 ,

Can you share the exact commands you are running to build and the URL you are using to load the quickstart app in the browser?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by palash14** [comment]
npm run clean && npm run build

**Comment by palashcn** [comment]
Hi,

I run this command on server sudo pm2 start server/index.js
but when i visit the link it's showing server not supported.
could you please help

**Comment by manjeshbhargav** [comment]
Hi @palash14 , @palashcn ,

Can you share a screenshot of what you see? And what is `sudo pm2 start server/index.js`? You should be running `npm start`.

Thanks,

Manjesh Malavalli
JSDK Team
