### ISSUE TITLE
Mute  all or selected remote participant whose end is too noisy

### ISSUE THREAD

**Issue by ravik3592** [twilio/video-quickstart-js#146]
Im having a coaching app., where coach have to mute one or all students whose end is noisy. right now i cant find any option to mute participant
I tried several options but no luck,
publication.track.enablePlayback = false;
publication.track.enablePlayback(false);
publication.enablePlayback = false;
publication.enablePlayback(false);

finally one solution worked but it muted only for coach. I have coach and 3 students and i muted student 1, student 1 is muted only for coach but 2 and 3 can hear student 1 voice.
publication.isEnabled = false;
publication.mediaStreamTrack.enabled = false;

Is there any option there to mute all/ selected remote participants.

links which i referred
https://github.com/twilio/video-quickstart-android/issues/193

**Comment by likhit-vivek** [comment]
@ravik3592 I don't work for twilio but we implemented the mute all feature in our project and we did it using sockets. I don't think Twilio provides any mechanism for this. So what we do is connect all the participants of a particular meeting to the same socket and whenever the admin clicks on 'Mute All', a new socket event will be emitted. When this event is received by the other participants, they will be muted automatically using JS.

**Comment by manjeshbhargav** [comment]
Hi @ravik3592 ,

As @likhit-vivek has mentioned in his comment, you would have to send a message from the coach (either through your own app-specific websocket or using Twilio Video data tracks) to the participant to mute their audio, and then call `LocalAudioTrack.disable()` for that participant.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ravik3592** [comment]
@likhit-vivek @manjeshbhargav  is there any code sample to achieve this?. i have no idea about websocket or datatracks implementation. It would be helpful if you can share which lights me to start

**Comment by likhit-vivek** [comment]
@ravik3592 Go through these two tutorials
https://tsh.io/blog/socket-io-tutorial-real-time-communication/
https://socket.io/get-started/chat/
Understand how to join someone to a socket and how to emit and catch socket events. This basic understanding should be enough to implement nodejs socket.io in ur server (backend).

If you are not using nodejs for ur backend, the above tutorials won't work for u. You have to investigate about the sockets available for the backend tech u r using.
