### ISSUE TITLE
How to allow some participants to view video and some will not view the Video of Participants

### ISSUE THREAD

**Issue by irshadhub** [twilio/video-quickstart-js#147]
I want to restrict some other participants to view the video of other participants using video-quickstart-js.

They can listen to other participants but they will not be able to see the video of them.

Please help me with this.

**Comment by manjeshbhargav** [comment]
Hi @irshadhub ,

You can use our [Track Subscriptions REST API](https://www.twilio.com/docs/video/api/track-subscriptions) to control who sees and hears what. I will close this issue, but we can continue the conversation here if you need any more clarification.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by irshadhub** [comment]
Hi manjesh,

can you please tell me, how can I not subscribe to specific track.
Suppose if have sid of participants and I don't want to subscribe to one of them using some code.

for example:
```
/**
 * Handle the Participant's media.
 * @param participant - the Participant
 * @param room - the Room that the Participant joined
 */
function participantConnected(participant, room) {
  // Set up the Participant's media container.
  setupParticipantContainer(participant, room);

  // Handle the TrackPublications already published by the Participant.
  participant.tracks.forEach(publication => {
    trackPublished(publication, participant);
  });

  // Handle the TrackPublications that will be published by the Participant later.
  participant.on('trackPublished', publication => {
    trackPublished(publication, participant);
  });

  if ( participant.sid != room.localParticipant.sid && $(`div#avbtn-${participant.sid}`).length > 0 ) {
    new Audio('../audio/success.mp3').play(); // Play if some one Connected to room
  }

  setParticipantCount(); // count of connected Participants
}

/**
 * Handle to the TrackPublication's media.
 * @param publication - the TrackPublication
 * @param participant - the publishing Participant
 */
function trackPublished(publication, participant) {
  // If the TrackPublication is already subscribed to, then attach the Track to the DOM.
  if (publication.track) {
    attachTrack(publication.track, participant);
  }

  // Once the TrackPublication is subscribed to, attach the Track to the DOM.
  publication.on('subscribed', track => {
    attachTrack(track, participant);
  });

  // Once the TrackPublication is unsubscribed from, detach the Track from the DOM.
  publication.on('unsubscribed', track => {
    detachTrack(track, participant);
  });
}
```

Is there any way to not subscribe by checking track kind is video and sid of the participant. It will help us to not subscribe to that particular track if not needed.

**Comment by irshadhub** [comment]
Hi Manjesh,

Can you please provide some details about this.

To not subscribe to that particular track if not needed.

Regards,
Irshad Khan

**Comment by manjeshbhargav** [comment]
Hi @irshadhub ,

You can connect to the Room with `automaticSubscription: false` in ConnectOptions so that no tracks are subscribed to initially. Then, you can use the [Track Subscription REST API](https://www.twilio.com/docs/video/api/track-subscriptions) to specify which tracks you want to subscribe to.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by irshadhub** [comment]
Hi Manjesh,

I tried your referred documentation but somehow it is not working. 

Please check the below code and tell me what is wrong, because it is giving an error on Join room Modal box.
The error is USER_FRIENDLY_ERRORS.TypeError meassge

```
async function joinRoom(token, connectOptions) {

    connectOptions.video.name = getVideoTrackName();

    connectOptions.automaticSubscription = false;

    // Join to the Room with the given AccessToken and ConnectOptions.
    const room = await connect(token, connectOptions);

    var myName = $('#screen-name').val();

    room.participants.get( myName ).subscribeRules.update({
        rules: [
            {"type": "include", "kind": "audio"}, // Audio allowed
            {"type": "include", "track": "screen"}, // SCreen Share Allowed
            {"type": "include", "publisher": "115_Admin", "kind": "video"} // one Video Allowed
        ]
    })
    .then(result => {
        console.log('Subscribe Rules updated successfully')
    })
    .catch(error => {
        console.log('Error updating rules ' + error)
    });
```
