### ISSUE TITLE
Video freeze issue with multiple participants

### ISSUE THREAD

**Issue by irshadhub** [twilio/video-quickstart-js#148]
We found this several times in our Video conferencing web project, which is using this library to connect Group rooms.

Some of us can see the frozen thumbnail of the participant but for some other participants it was not frozen. The Audio is coming properly but the video is getting stuck automatically.

Please tell us, how we can fix this freezing issue of video.

**Comment by manjeshbhargav** [comment]
Hi @irshadhub ,

Thanks for writing in with your issue. Can you describe the steps to reproduce this problem on our end? Also, what browser + OS versions are you using?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by irshadhub** [comment]
We are using Windows 10 and Chrome 83 version

The thumbnails of video boxes are visible to all participants. So at the beginning of the conference, we were muted our Audio and video. 

one by one we started un-muting our audio and video. As we were talking the Green color border was coming over the video thumbnails.

After a few minutes, we observed 2 participants video is in the freeze mode but we were able to hear them.

**Comment by manjeshbhargav** [comment]
Hi @irshadhub ,

Can you share some Room SIDs where this happens, along with a video recording of your app window?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by irshadhub** [comment]
Hi Manjesh,

Please check below details for your analysis:

**UNIQUE NAME:**  10046
**ROOM SID:**  RMaff6cb318e725c77dec2d155c5620887

**Comment by irshadhub** [comment]
Hi Manjesh,

Any update on this issue.
