### ISSUE TITLE
Issues in group room and small group room when only 2 participants are connected.

### ISSUE THREAD

**Issue by likhit-vivek** [twilio/video-quickstart-js#149]
If only 2 participants are using the meeting, after 2-3 min the audio is getting disconnected and sometimes total communication b/w the two participants is lost. Meeting needs be reloaded to work again.

I'm guessing it's because there won't be any audio or video change detected reg dominant speaker, and the tracks maybe getting expired or something.

Pls provide a solution for this? Whether to use a different kind of room in case of 2 participants or change some track detection logic. Thanks.

**Comment by manjeshbhargav** [comment]
Hi @likhit-vivek ,

Thanks for writing in with your issue. Can you please share some Room SIDs so we can start investigating?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by likhit-vivek** [comment]
Hi @manjeshbhargav. Thank you for replying. This is the room data. Pls look into it. Thanks.
```{
  "sid": "RM15e75216622b8881926ba4198e3b4790",
  "room": "114490485710_cV93bjXxz",
  "created_at": "2020-07-08T04:00:34.097Z"
}

**Comment by manjeshbhargav** [comment]
Hi @likhit-vivek ,

In the Room that you shared with me, I see the same lone Participant (identity: `{"user_name":"Chanikya Mandapati","image":"1588907400270VmbgvXdvmE.jpg","is_host":true}`) joining 4 times, and there were no other Participants. Can you share a different Room?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by likhit-vivek** [comment]
This issue is happening with every room we created. So, I think you can test it yourself by creating a new room and testing with only 2 participants. 

In our logic, we are ending the rooms after certain period of time, so when you asked for a room sid, we created a new room and sent it to you. We didn't use that room. Maybe that's why you are seeing only one user in that room.

Till last week, we were using twilio but since we're getting issues, we started testing another video conferencing sdk this whole week. So, we don't have any active twilio rooms right now. 

If you could tell me what information you are expecting from a room sid, maybe we can use twilio meeting again and get that information for you.

Thanks,
Vivek.

**Comment by likhit-vivek** [comment]
Hello @manjeshbhargav 

Any updates reg the issue?
