### ISSUE TITLE
Create the "invite" event

### ISSUE THREAD

**Issue by GlobalvoicesGabriele** [twilio/video-quickstart-js#15]
Hi,
Do you know if is possible use some "invite" event in order to ask to the people connected to the room to answer at the call incoming before start the conversation?
Or more in general just how create a new event.

Thank you

**Comment by markandrus** [comment]
We have [an example](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) using [Twilio Notify](https://twilio.com/notify) for our Android Video SDK. We need to create a similar one for twilio-video.js.

**Comment by Govind13100** [comment]
Hi, 

I have the same issue, you guys have solved it ? Is there any invite event ?

**Comment by manjeshbhargav** [comment]
Hi @Govind13100 ,

Thanks for writing in with your question. We don't this as part of our roadmap at this point. However, you can achieve this yourself by using [Twilio Notify](https://twilio.com/notify) in conjunction with our Video SDK.

Thanks,

Manjesh Malavalli
JSDK Team
