### ISSUE TITLE
Got error in npm i

### ISSUE THREAD

**Issue by kau1992** [twilio/video-quickstart-js#150]
I got below error in **npm i** command

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@twilio%2fwebrtc - Not found
npm ERR! 404 
npm ERR! 404  '@twilio/webrtc@4.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'twilio-video'

I used below Node version
Node Version  = 12.16.1

**Comment by PikaJoyce** [comment]
Hey there, 

Thank you for opening this issue. I see you closed the same issue on twilio-video repo. So I will close this as well. If you have any further questions, feel free to comment here! 

Regards,
Joyce
