### ISSUE TITLE
This demo is not supported on iPadOS

### ISSUE THREAD

**Issue by TravBradfield** [twilio/video-quickstart-js#151]
I installed and ran this test app on my machine. All works well. I then wanted to test and compare the example to my own Angular implementation of the Twilio video. 

Using ngrok to view the demo on my iPad I receive this error: 

![IMG_F0DFAD6093F2-1](https://user-images.githubusercontent.com/32768356/89529772-2ff09500-d7e5-11ea-87b2-40411f928d90.jpeg)

Is this as you expect? Are you sure you don't support iPad? My Angular implementation supports all platforms fine, I wanted to test the camera selection tool to see if it would apply a different camera to the room joining. I'm currently not able to specify which device my app uses as the camera device.

**Comment by PikaJoyce** [comment]
Hey @TravBradfield!

Thank you for opening this issue with us. It seems that you may not be on either a **localhost** or **https* domain. We rely on `getUserMedia` which is only available in secure contexts. Please refer to our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#application-domain) for more details.

I hope this answers your question. I will be closing this issue now, but please feel free to comment below if you're still experiencing problems! 

Best,
Joyce

**Comment by TravBradfield** [comment]
> Hey @TravBradfield!
> 
> Thank you for opening this issue with us. It seems that you may not be on either a **localhost** or **https** domain. We rely on `getUserMedia` which is only available in secure contexts. Please refer to our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#application-domain) for more details.
> 
> I hope this answers your question. I will be closing this issue now, but please feel free to comment below if you're still experiencing problems!
> 
> Best,
> Joyce

Thanks @PikaJoyce you are correct. I have managed to solve the problem!
