### ISSUE TITLE
Unable to the join video room without giving any of  audio or video access permission or both.

### ISSUE THREAD

**Issue by imbiswajit** [twilio/video-quickstart-js#154]
Currently I am facing an issue like if I don't give any audio or video permission or both, then I am getting some error. 

Is there any way to bypass this permission things and overcome with like if the user gives permission or not, the user can join the video room?

How to work on this scenario?

Please help me on this one. Thanks in advance.

**Comment by makarandp0** [comment]
Hey @imbiswajit, 

Do you want want user to be able to join the room even when they decline audio/video permissions right? You can do so by acquiring tracks to be published outside  `Video.connect` call, and pass them to Video.connect explicitly.

Something like:
```js
const { createLocalTracks, connect } = require('twilio-video');

const tracks = [];
try {
   tracks = await createLocalTracks(...)
} catch (ex) {
  console.log("createLocalTracks failed. perhaps user denied permissions")
  tracks = [];
}

const room = await connect(token, { tracks } )
```

With this the user will join the room w/o any tracks if they do not grant permission to acquire tracks.


Thanks,
Makarand

**Comment by vinaynb-at** [comment]
@makarandp0 Hi facing a similar issue here. I am using the code you suggested above and while there are no errors and all is good in js console, If i do not give either of audio or video, the remote participants tracks are not being streamed to the user as they should be. Is this by design ?

**Comment by rxcod9** [comment]
> @makarandp0 Hi facing a similar issue here. I am using the code you suggested above and while there are no errors and all is good in js console, If i do not give either of audio or video, the remote participants tracks are not being streamed to the user as they should be. Is this by design ?

I believe, you can join room without audio and video and watch others or present your screen through screen track
If you’re using data tracks, you’ll be able to text chat the participants
