### ISSUE TITLE
This browser is not supported.

### ISSUE THREAD

**Issue by pk4all** [twilio/video-quickstart-js#155]
Getting error on live server
![2020-09-11](https://user-images.githubusercontent.com/12910992/92903028-60a89780-f43f-11ea-9034-1714ded611b7.png)

**Comment by PikaJoyce** [comment]
Hi @pk4all! 

Thank you for opening this issue with us. It seems that you may not be on either a **localhost** or **https** domain. We rely on getUserMedia which is only available in secure contexts. Please refer to our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#application-domain) for more details.

I hope this answers your question. I will be closing this issue now, but please feel free to comment below if you're still experiencing problems!

Best,
Joyce

**Comment by Marcanaster** [comment]
I am getting the following error at the moment that I call the API for token.
![image](https://user-images.githubusercontent.com/12750137/215282232-a163a0b2-af70-453f-a34e-98287003afea.png)
