### ISSUE TITLE
Black video screen when processing RemoteVideoTrack.

### ISSUE THREAD

**Issue by PavloShchur** [twilio/video-quickstart-js#158]
**Problem Description**

When local participant tries to attach RemoteVideoTrack to the DOM black video screen is displayed instead of actual video.

**Logic Description**

We create video track by using `Twilio.Video.createLocalVideoTrack` function.

We publish video track in the following way: `await currentRoom.localParticipant.publishTrack(track, {priority : 'low'});`

We handle track publication in the following way: 
`participant.on('trackSubscribed', track => {
                processTrack(participant, track);
            });`

The 'processTrack' function just attaches the track and adds it to the DOM.

Before attaching it.

![image](https://user-images.githubusercontent.com/25909788/97603265-eb0b8180-1a14-11eb-836d-da4de61b3098.png)

**Additional Information**

"maxTracks" attribute in the "bandwidthProfile" is set to 6.

"automaticSubscription" is set to "true".

twilio-client.js 1.10.3

Room-Sid: RM8dd122890ec445190758376a267c9faf

No one error/warning logs were found on client side.

We use approach described here:

https://www.twilio.com/docs/video/javascript-v2-getting-started#display-a-remote-participants-video

**Comment by OlehChuyko** [comment]
Same issue affects me

**Comment by Misha1Shevchuk** [comment]
It also affects me. Are there any info how to fix this?

**Comment by bohdandovhan** [comment]
Same issue affects me. Please let me know if anyone has found any kind of workaround

**Comment by Znakas** [comment]
We have similar problem, are there any updates?

**Comment by PavloShchur** [comment]
Could it be related to Autoplay Policy?
https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#autoplay-policy

**Comment by manjeshbhargav** [comment]
Hi @PavloShchur ,

One way you can get around the autoplay policy is to join a Room only after the user clicks on a button. Please try that and let me know. I will close the issue for now, but we can continue our conversation here.

Thanks,

Manjesh
