### ISSUE TITLE
Any guidance on muting audio and toggle video 

### ISSUE THREAD

**Issue by DAC696** [twilio/video-quickstart-js#159]
Hello there i am a bit new on handling twilio i couldnt find anything on webjs for video audio mute for the sample 
If any one could point me to the right direction or help would really appreciate that

I have deployed the sample to heroku 
and its working fine 
just need something to mute audio and toggle video

**Comment by anna-vasilko** [comment]
Hi @DAC696,
Thanks for reaching out. Here is [an example](https://www.twilio.com/docs/video/javascript-getting-started#mute-and-unmute-audio-and-video) of how to implement muting audio and video tracks. 
Hope it is helpful.
