### ISSUE TITLE
cant switch between two camera's and If I manage to switch then it is broadcasting from only one(default) camera.

### ISSUE THREAD

**Issue by KiranAdroit** [twilio/video-quickstart-js#16]
Hello, 
I am using Twilio to broadcast a video and I have option for choosing camera. It is showing all options (camera's) but when I switch between them , then it is broadcasting from the default camera and from I chosed.

**Comment by KiranAdroit** [comment]
Hi Vsrboth,

I had the same issue. I was not able to broadcast from back camera(if on mobile) or any other camera except default one. So I modified applyVideoInputDeviceSelection function to 

function applyVideoInputDeviceSelection(deviceId, video) {
    return Video.createLocalVideoTrack({
      deviceId: deviceId,
      height: 240,
      width: 320
    }).then(function(localTrack) {
      localTrack.attach(video);
    });

  }

And now it is working for me. I can switch and broadcast from the selected camera.

**Comment by vsrboth** [comment]
Hi @KiranAdroit 
Thanks for the help. I am unable to make it work with the above codes, yet keep encountering `constraint error` issue:

<img width="989" alt="screen shot 2017-11-20 at 2 31 22 pm" src="https://user-images.githubusercontent.com/5484995/33020740-9fa77e92-cdff-11e7-9b52-2204052af914.png">

```
Twilio.Video.createLocalVideoTrack(
        deviceId: $(this).val()
        height: 240
        width: 320
      ).then (localTrack) ->
        localTrack.attach video
        return
```

**Comment by markandrus** [comment]
Hi @KiranAdroit,

Can you clarify how you get the `deviceId`? I tried answering @vsrboth's related question over [here](https://github.com/twilio/twilio-video.js/issues/218) by suggesting to use the `facingMode` constraint.

Otherwise, it sounds like this issue is solved, so I'll close it. If you have further questions, feel free to re-open this issue or open a new one.

Best,
Mark

**Comment by KiranAdroit** [comment]
@markandrus,
I followed this link to get deviceId of the selected device.
https://www.twilio.com/docs/api/video/javascript

Video.createLocalTracks(
        {
          video: {deviceId: deviceSelections.videoinput.value},
          audio: {deviceId: deviceSelections.audioinput.value},
        }

**Comment by vsrboth** [comment]
@KiranAdroit this might depends on the gadgets. As for me, using `facingMode` is working fine.
