### ISSUE TITLE
 I can't share screen

### ISSUE THREAD

**Issue by oscarcornejo** [twilio/video-quickstart-js#161]
Hi, I can't share the screen, I just open the options window to select a window, I select a window, but the other person cannot see my shared screen, only I can see the screen that I selected.

I am using ReactJs and implemented these methods:

```
const createScreenTrack = (height, width) => {
    if (typeof navigator === 'undefined' || !navigator.mediaDevices || !navigator.mediaDevices.getDisplayMedia) {
      return Promise.reject(new Error('getDisplayMedia not supported'));
    }

    return navigator.mediaDevices
      .getDisplayMedia({
        video: {
          frameRate: 10,
          aspectRatio: 1.5,
          height: height,
          width: width,
        },
      })
      .then(function (stream) {
        return new Video.LocalVideoTrack(stream.getVideoTracks()[0]);
      });
  };
```

```
const captureScreen = async () => {
    let screenTrack;
    
    try {
      // Create and preview your local screen.
      screenTrack = await createScreenTrack(1080, 1920);
      screenTrack.attach(screenPreview);
    } catch (e) {
      console.log(e.message);
    }
  };
```

**Comment by PikaJoyce** [comment]
Hey @oscarcornejo!

Thanks for submitting this issue. Do you have any errors that are showing for you on the console? 

Also, have you checked out the [React App](https://github.com/twilio/twilio-video-app-react) which utilizes the screen share feature [here](https://github.com/twilio/twilio-video-app-react/blob/master/src/hooks/useScreenShareParticipant/useScreenShareParticipant.tsx)?

**Comment by PikaJoyce** [comment]
Closing this issue to continue the discussion [here](https://github.com/twilio/twilio-video.js/issues/1302).

**Comment by oscarcornejo** [comment]
Hello! Closing the incidents without having a feedback does not help much, at the moment I continue with the problem, the documentation that you provide is very bad, I cannot share and stop the screen with other participants.

**Comment by PikaJoyce** [comment]
Hey @oscarcornejo!

I apologize for that. Of course, I am happy to help and debug with you if possible. I closed this issue as it seems like there are two issues you've opened about this issue. So to keep things easier, would you prefer to continue the discussion on this thread rather than the other [issue](https://github.com/twilio/twilio-video.js/issues/1302) you've opened? 

Please do let me know and I'll do my best to try to help out! 

Thanks!
Joyce

**Comment by umerdev228** [comment]
Hello @PikaJoyce 
room.localParticipant.publishTrack(screenTrack);
when I publish this it show my camera preview again. It is now showing my screen.





My Code is in VUEJS 
getAccessToken: function () {
      const _this = this
      const axios = require('axios')

      // Request a new token
      axios.get('/api/access_token')
          .then(function (response) {
            _this.accessToken = response.data
          })
          .catch(function (error) {
            console.log(error);
          })
          .then(function () {
            _this.connectToRoom()
          });
    },
    connectToRoom: function () {
      let self = this
      const {connect, createLocalVideoTrack} = require('twilio-video');
      connect(this.accessToken, {audio: self.microphone, video: {width: 150}, name: 'myRoom'}).then(room => {
        const videoChatWindow = document.getElementById('video-chat-window');

        self.room = room
        self.createLocalVideoTrack = createLocalVideoTrack

        room.on('participantConnected', participant => {
          participant.on('trackSubscribed', track => {
            let section = document.createElement('div');
            section.setAttribute("id", participant.identity);
            section.setAttribute("class", "p-2 second");
            videoChatWindow.appendChild(section);
            section.appendChild(track.attach());
            // videoChatWindow.appendChild(track.attach());

          });
        });

        room.participants.forEach(participant => {
          let section = document.createElement('div');
          section.setAttribute("id", participant.identity);
          section.setAttribute("class", "p-2 hello");
          videoChatWindow.appendChild(section);
          participant.on('trackSubscribed', track => {
            section.appendChild(track.attach());
            // videoChatWindow.appendChild(track.attach());
          });
        });

        // When a Participant leaves the Room, detach its Tracks.
        room.on("participantDisconnected", function(participant) {
          self.detachParticipantTracks(participant);
          console.log(participant.identity + " left the room");
        });


        // Log your Client's LocalParticipant in the Room
        const localParticipant = room.localParticipant;
        console.log(`Connected to the Room as LocalParticipant "${localParticipant.identity}"`);

        // Log any Participants already connected to the Room
        room.participants.forEach(participant => {
          console.log(`Participant "${participant.identity}" is connected to the Room`);
        });

      }, error => {
        console.error(`Unable to connect to Room: ${error.message}`);
      });
    },


    screenShare() {
      let self = this
      const videoChatWindow = document.getElementById('video-chat-window');
      navigator.mediaDevices.getDisplayMedia({
        mediaSource: 'window'
      }).then(function (stream) {
        console.log(stream)
        self.createLocalVideoTrack(stream.getTracks()[0]).then(function (screenTrack) {
          console.log(screenTrack)
          self.room.localParticipant.publishTrack(screenTrack);
          
        });
      });
    }

**Comment by umerdev228** [comment]
@PikaJoyce
My Video Calling working fine but this issue 
When I share screen it ask for allow but share camera preview again to the participants
