### ISSUE TITLE
navigator.mediaDevices does not exist.

### ISSUE THREAD

**Issue by RyanSacks** [twilio/video-quickstart-js#162]
Hi,
I'm more interested in Twilio's Programmable Video API, but for that and this quickstart I'm getting the same issues, all of my browsers (not just Chrome) are having trouble detecting my video.
I'm using a Macbook Pro (Laptop), MacOS Mojave Version 10.14.6 (18G6032), Chrome Version 87.0.4280.67 (Official Build) (x86_64). No matter what browser I try this in (Chrome, Safari, Firefox) I get this error:
navigator.mediaDevices does not exist.

My camera is working though. I use it for Zoom meetings all the time.
I'm also using an Ngrok tunnel to serve the url over https so I know that is not the issue.
Attached is a screenshot of the error.
Thank you.

![video-quickstart-js-chrome-error-screenshot](https://user-images.githubusercontent.com/48108073/100164816-ae516f80-2e86-11eb-94a2-b1356fd922d2.jpg)

**Comment by PikaJoyce** [comment]
Hi @RyanSacks!

Thank you for opening this issue. Can you please open your console and let me know if there is an error message there? If so, what the error message there says? 

Regards,
Joyce

**Comment by RyanSacks** [comment]
Hi Joyce
There's no error message in the console. It just says:
Successfully joined a Room: [Room #1: RMf0d02d18ac8fa4c9b5f70b79b7b0e820]
Participant "5fc94c8a8a69e" connected

For some reason the video in that second black box isn't playing. Are there
Twilio error logs you can look at?

**Comment by PikaJoyce** [comment]
Hi @RyanSacks 

Thanks for getting back to me with this information. I see that there are some ICE failures. I am assuming that you have granted your browsers permissions to use your camera and microphone, if not, can you please ensure that the your browsers have permission to access your camera and microphone? 

If your browsers have permissions, I'm wondering if you can try this [WebRTC Troubleshooter](https://test.webrtc.org/) and let me know if there is any useful information? 

Thanks again,
Joyce

**Comment by RyanSacks** [comment]
Yes, it prompted me on both my laptop and phone for permissions, the
browsers have permissions. I tried the link, there were a couple of
failures. See screenshot attached.

**Comment by PikaJoyce** [comment]
Hey @RyanSacks, 

Thanks for trying it out! But it doesn't seem like an image was attached to your last message. 

Best,
Joyce

**Comment by RyanSacks** [comment]
It shows up for me, but here it is again.

**Comment by PikaJoyce** [comment]
Hm, I'm sorry, it seems I still don't see an image on github or through email.

**Comment by RyanSacks** [comment]
I'm sending you a wetransfer. You can download it from there.

**Comment by RyanSacks** [comment]
Sorry what's your email address?

**Comment by PikaJoyce** [comment]
Hey! 

Could you please try using the site and uploading the image there? I noticed that you're replying to this thread through email which might be why the image isn't uploading to GitHub. 

However, if that still doesn't work, you can try sending the image to joma@twilio.com.

Thanks!
Joyce

**Comment by PikaJoyce** [comment]
Hey there @RyanSacks,

I'm going to close this issue as it's been inactive for some time now. 

Best,
Joyce
