### ISSUE TITLE
Can i integrate Tensorflow.js libraries in web app created  by Twilio Video

### ISSUE THREAD

**Issue by Aayush795** [twilio/video-quickstart-js#163]
i have implemented and deployed this repo https://github.com/elizabethsiegle/twilioVideoWebChat9Mins,  however i wanted to know if I can integrate tensorflow js with this code for face detection in all the streams of the participants that join the room? basically something that sends the notification if the face goes out of frame..i wanted to use Tensorflow.js. is it possible? if yes, how do i access the video stream link? Thanks

**Comment by manjeshbhargav** [comment]
@Aayush795 ,

Please check out the [localvideofilter](https://github.com/twilio/video-quickstart-js/tree/master/examples/localvideofilter) quickstart example on how to access video frames from a track.

Thanks,

Manjesh
