### ISSUE TITLE
Is it possible to track an audio event?

### ISSUE THREAD

**Issue by pikaclint** [twilio/video-quickstart-js#165]
Hi would like to know if for example my own audioTrack is muted and I started speaking while muted it can return an event, this will be similar to teams to tell you that you are muted.

Probably the general question if we are able to track AudioEvents while speaking? Because I believe that dominant speaker is the only audio speaking event I see on Twilio. Any hints in obtaining the audio speaking event would be great.

**Comment by manjeshbhargav** [comment]
Hi @pikaclint ,

The only way you can do that in my view is by using the Web Audio APIs and inspecting the audio samples and detecting speech. You can find examples online.

Thanks,

Manjesh
