### ISSUE TITLE
Remote participant's video is blank/empty

### ISSUE THREAD

**Issue by akshayKhot** [twilio/video-quickstart-js#167]
Hello,

My application uses Twilio Programmable Video to allow participants to have video calls with each other. Everything worked fine till last month. Suddenly, the remote participant's video started showing up blank on the phone, as seen in the screenshot below. It works on Desktop and shows both local and remote participants, just not on the phone. 

![Twilio](https://user-images.githubusercontent.com/14203386/106484032-35e5db00-64d5-11eb-9e55-787eff51c50c.jpg)

First, I thought it was a bug in my code, but I couldn't find it even after a thorough code review. Moreover, I could reproduce the problem by switching to the old version of the code which did work. 

Then I cloned the sample application provided in this repository and noticed that I can reproduce the problem. To reproduce, just follow all the instructions in the readme. Then, use ngrok to expose the endpoint and navigate to it using your phone. Once you join the same room, you will notice that the remote video is empty on the phone, though it seems to work on the desktop, which is weird, since it's the same codebase. 

I am not sure if anybody else has noticed this, or this problem is specific to my environment/browser/phone (which seems unlikely, as I tested this on two separate phones, on multiple browsers). 

We have customers waiting for this problem to get sorted soon. Any help is really appreciated. 

Please let me know if you need any other information from me to reproduce this problem. 

Thanks,
Akshay

**Comment by akshayKhot** [comment]
Is there any update on this? @manjeshbhargav @philnash @makarandp0 

Let me know if you need any other details to reproduce this behavior. 

Thanks, 
Akshay

**Comment by PikaJoyce** [comment]
Hi @akshayKhot,

Thank you for submitting this issue. 

I have just tested this on my own device and was not able to reproduce your issue 
![image](https://user-images.githubusercontent.com/43423318/106814001-95073500-6626-11eb-845d-8c83054efa82.png)

Is it possible for you to share what your device is, OS, as well as browser you are using in order to run the application?

Best,
Joyce

**Comment by akshayKhot** [comment]
I am using the Chrome on Macbook air, Safari on iOS, and Chrome on Android phone. All the browsers are on the latest versions.

**Comment by PikaJoyce** [comment]
Thank you for responding, @akshayKhot.

I was wondering if it's also possible for you to share some room sids where this is happening so I can take a look at our logs and hopefully provide more insight as to why this is happening.

Regards,
Joyce

**Comment by akshayKhot** [comment]
Hi @PikaJoyce, 

Sorry for the late reply, I was away traveling. I tested the video and seems to be working again, without any code/app changes. 

I will update you with further details if I can reproduce the behavior consistently in the future. Closing the issue for now. 

Thanks for looking into this. I really appreciate it. 

Regards,
Akshay
