### ISSUE TITLE
Integration of mute/unmute video enable/disable in JS

### ISSUE THREAD

**Issue by thrustonline** [twilio/video-quickstart-js#168]
Hi,

I have integrated the quickstart code in my .NET app, but unable to integrate mute/unmute code from the examples?
mute/unmute example does not contain room select and join. Can you guide on this?

Regrds,
Niraj

**Comment by manjeshbhargav** [comment]
Hi @thrustonline ,

Our [local media controls](https://github.com/twilio/video-quickstart-js/blob/master/examples/localmediacontrols/src/index.js) example app does indeed have room join/leave. You should be able to refer to it and integrate it into your app easily.

Thanks,

Manjesh
