### ISSUE TITLE
How to mute the local microphone in a Twilio Video browser app in Javascript ?

### ISSUE THREAD

**Issue by MBuLoft1** [twilio/video-quickstart-js#17]
We would like turn off the local microphone in our browser application. Is this possible in the Javascript client SDK for Twilio Video, and how ?

**Comment by MBuLoft1** [comment]
Ok, here is how I do it...

```
Twilio.Video.connect(accessToken, connectOptions).then(onRoomJoined, function (error) {
console.log(error)
});

...

function onRoomJoined(room) {
    var localParticipant = room.localParticipant;
    localParticipant.audioTracks.forEach(function (audioTrack) {
       audioTrack.disable();
    });
    localParticipant.videoTracks.forEach(function (videoTrack) {
       videoTrack.disable();
    });
    ...
}
```

**Comment by MikeSha** [comment]
Doesn't work for me :(

**Comment by markandrus** [comment]
@MBuLoft1's example is correct—calling `disable` should mute the LocalAudioTracks (or pause the LocalVideoTracks). If you want to stop capturing the microphone completely, you can call `stop` on the LocalAudioTrack (or, to stop capturing the camera completely, `stop` on the LocalVideoTrack).

@MikeSha I know this is an old ticket, but are you still having trouble? If so, feel free to re-open this issue or open a new one.

Thanks,
Mark

**Comment by Kok357357** [comment]
works for me

**Comment by akshukla07** [comment]
For me, the given examples did not work on ionic framework v3. I had to modify it to the following:
`this.activeRoom.localParticipant.audioTracks.forEach((trackMap) => {
        trackMap.track.enable(); // or .disable()
});`

**Comment by ericksondelacruz** [comment]
Turn Off Audio
```
room.localParticipant.audioTracks.forEach((publication) => { 
    publication.track.disable(); 
});
```

Turn On Audio
```
room.localParticipant.audioTracks.forEach((publication) => { 
    publication.track.enable(); 
});
```

Turn Off Video
```
room.localParticipant.videoTracks.forEach((publication) => { 
    publication.track.disable(); 
});
```

Turn On Video
```
room.localParticipant.videoTracks.forEach((publication) => { 
    publication.track.enable(); 
});
```

**Comment by bhattaxay** [comment]
@ericksondelacruz  i have followed you method but it do not works for me. I don't know what is wrong with it.
```
const publications = kind === 'audio'
    ? room.localParticipant.audioTracks
    : room.localParticipant.videoTracks;
  publications.forEach(function(publication) {        
    console.log( 'publication:'+publication );
    if (action === 'mute') {
      publication.track.disable();
      console.log( 'mute pubication:'+publication.track );
    } else {
      publication.track.enable();
      console.log( 'unmute pubication:'+publication.track );
    }
  });
```

**Comment by Kok357357** [comment]
@bhattaxay

**Comment by Kok357357** [comment]
> @ericksondelacruz i have followed you method but it do not works for me. I don't know what is wrong with it.
> 
> ```
> const publications = kind === 'audio'
>     ? room.localParticipant.audioTracks
>     : room.localParticipant.videoTracks;
>   publications.forEach(function(publication) {        
>     console.log( 'publication:'+publication );
>     if (action === 'mute') {
>       publication.track.disable();
>       console.log( 'mute pubication:'+publication.track );
>     } else {
>       publication.track.enable();
>       console.log( 'unmute pubication:'+publication.track );
>     }
>   });
> ```

@bhattaxay
Can you provide console log?

**Comment by Kok357357** [comment]
https://github.com/twilio/video-quickstart-js/issues/17#issuecomment-626684504

**Comment by Kok357357** [comment]
Can you provide detailed console log?
Actually it seems that there is no issue on your code.
Maybe there is issue on your twilio connection?

**Comment by bhattaxay** [comment]
Hii,

I got the solution. The issue was i check it with different room twilio
token. That's why it was not working. Thank you for your reply

**Comment by wangdanyang711** [comment]
Thanks it works for me~

**Comment by omairshamshir** [comment]
@Kok357357  I tried you solution but it is not working for me. Can you please help?

```
useEffect(() => {
        if (mute) {
            room.localParticipant.audioTracks.forEach((publication: any) => {
                publication.track.disable();
            });
        } else {
            room.localParticipant.audioTracks.forEach((publication: any) => {
                publication.track.enable();
            })
        }
    }, [mute]);
```
But the audio is still working and the remote participants can still hear my voice, do I need to do anything else in addition to this

**Comment by Muzaffar-Munir** [comment]
I am new to Twilio and I am using Laravel and vuejs. now I have the same issues and the above solution is not working in my case.

Here is my **code** for mute audio and disable videos
`mute() {
            console.log("in mute");
            this.activeRooms.localParticipant.audioTracks.forEach(publication => {
                // publication.track.mediaStreamTrack.muted.disable();
                publication.track.disable();
            });
            this.activeRooms.localParticipant.videoTracks.forEach(publication => {
                // publication.track.disable();
                 publication.track.stop();
                publication.unpublish();
            });

        },`

and for allow/disable video 

`
 toggleVideo:  function(){
           this.videoStatus = !this.videoStatus;
            console.log(this.videoStatus);
            // Video toggle event handler
       if (this.videoStatus) {
           this.activeRooms.localParticipant.videoTracks.forEach(videoTrack => {
               videoTrack.track.disable();
               console.log(videoTrack.track.disable());
           });
       } else {
           this.activeRooms.localParticipant.videoTracks.forEach(videoTrack => {
               videoTrack.track.enable();
                console.log(videoTrack.track.enable());
           });
       }
`
``

**Comment by muhamedoufi** [comment]
> @ericksondelacruz i have followed you method but it do not works for me. I don't know what is wrong with it.
> 
> ```
> const publications = kind === 'audio'
>     ? room.localParticipant.audioTracks
>     : room.localParticipant.videoTracks;
>   publications.forEach(function(publication) {        
>     console.log( 'publication:'+publication );
>     if (action === 'mute') {
>       publication.track.disable();
>       console.log( 'mute pubication:'+publication.track );
>     } else {
>       publication.track.enable();
>       console.log( 'unmute pubication:'+publication.track );
>     }
>   });
> ```

This worked but only at remote participiant (remote participiants show you disable video )  but at you video still
