### ISSUE TITLE
İnvalid Token Error

### ISSUE THREAD

**Issue by borahanarslan** [twilio/video-quickstart-js#172]
Hello there,
I could not find what I am doing wrong. I installed nmp,
I edited env.template,

but I keep getting token errors
my url: http://localhost:3000/quickstart/
![envTemplate](https://user-images.githubusercontent.com/14363652/108714994-4ebd3b80-752b-11eb-802d-472e51976356.png)

![ErrorTwillio](https://user-images.githubusercontent.com/14363652/108714742-fc7c1a80-752a-11eb-9547-c0836ccc6fe0.PNG)

**Comment by PikaJoyce** [comment]
Hi @borahanarslan !

Thank you for opening this issue with us. I noticed that you are editing the `.env.template`. Please create a separate file using this `cp .env.template .env` and then you can edit the `.env` file with your token. Let me know if this works for you!

Best,
Joyce

**Comment by borahanarslan** [comment]
> Hi @borahanarslan !
> 
> Thank you for opening this issue with us. I noticed that you are editing the `.env.template`. Please create a separate file using this `cp .env.template .env` and then you can edit the `.env` file with your token. Let me know if this works for you!
> 
> Best,
> Joyce

Yes, it worked now
Thank you @PikaJoyce

**Comment by PikaJoyce** [comment]
Hi @borahanarslan 

You're very welcome! I'm going to close this issue now, but do feel free to open another or comment on this thread if you have any other issues in the future :). We can't wait to see what you build!

Best, 
Joyce

**Comment by borahanarslan** [comment]
Hi @PikaJoyce 
I posted the files to the server, rebuild token. But it gave the same error again. Is there any other extra setting I need to make in the server?
https://ibaproject.com/quickstart/public

**Comment by PikaJoyce** [comment]
Hey @borahanarslan,

I'm sorry to hear that it is still not working for you. Could you describe more about what you mean by posting to the server? Also, out of curiosity, would it be possible you have `ENV` variables that are being used with the same name and invalid credentials? 

Regards,
Joyce

**Comment by borahanarslan** [comment]
Hi @PikaJoyce ,
I mean **http://localhost:3000** yes it works, 
but when i install hosting (windows server 2012) it doesn't work **https://ibaproject.com/quickstart/public**
created new ENV
Anyway we will use webRTC. Twilio I think it will make us tired and sad. Thank you for trying to help, though.
Thanks

**Comment by PikaJoyce** [comment]
Hi @borahanarslan,

Please double check the environment variables on your server. You can see what credentials you are using by logging [this](https://github.com/twilio/video-quickstart-js/blob/master/server/index.js#L70)in your server. Here you can ensure whether or not the proper credentials are being passed into your app.

I am sorry to hear about your experience. Please do let us know if we can improve our onboarding experience, and how. We'd love to hear your thoughts. We are constantly striving to improve.

And again, let me know if there's anything else I can help you with.

Best,
Joyce
