### ISSUE TITLE
Implementing  to Netlify(help needed)

### ISSUE THREAD

**Issue by instantwpuserwin** [twilio/video-quickstart-js#175]
This works well in local.

How to Implement to Netlify?
I tried to implment to Netlify. But preview gives page not found.

My Netlify settings:
Base directory: Not set
Build command: npm run build:quickstart
Publish directory: quickstart
  
Please help. Thanks

**Comment by instantwpuserwin** [comment]
App url:
https://603b84dbe4f028677a2dd1ad--upbeat-bassi-828cc1.netlify.app/

**Comment by PikaJoyce** [comment]
Hi @instantwpuserwin,

I apologize for the extremely delayed response. But there has not been another response on this issue in some time. We unfortunately don't use Netlify. However, we do have a [nifty blog post](https://www.twilio.com/blog/a-how-to-send-text-messages-from-your-static-site-using-netlify-twilio-and-serverless-functions) on how to do what you're doing but with SMS. 

We also offer [Serverless Deployment](https://www.twilio.com/docs/labs/serverless-toolkit). Which our [React App](https://github.com/twilio/twilio-video-app-react) currently utilizes.

Please take a look at these resources and I hope they're helpful. However, I will be closing this issue as there are no current action items from this issue. Do feel free to open another issue if you have further questions.

Best,
Joyce
