### ISSUE TITLE
Quickstart on localhost is no longer working on localhost (navigator.mediaDevices does not exist)

### ISSUE THREAD

**Issue by lhamoudi** [twilio/video-quickstart-js#177]
Same as https://github.com/twilio/video-quickstart-js/issues/157

I swear this used to work for me as a simple test bed. But now following a pull, it doesn't. When I join the room I get 

TypeError: Cannot read property 'getLogger' of undefined
Cause:
navigator.mediaDevices does not exist.

Solution:
If you're sure that the browser supports navigator.mediaDevices, make sure your app is being served from a secure context (localhost or an https domain).

**Comment by manjeshbhargav** [comment]
@lhamoudi I think updating the ask should solve the issue. Please nuke your node_modules and package-lock.json and run npm install again. That should solve the issue.

**Comment by lhamoudi** [comment]
Yeah that was it Manjesh I'm a dummy. Neglected to npm install again after a pull.
