### ISSUE TITLE
Video + Chat

### ISSUE THREAD

**Issue by mushzak** [twilio/video-quickstart-js#178]
Can you tell me please how to add chat here? 
![image](https://user-images.githubusercontent.com/14214670/110531785-715b7100-8135-11eb-94f0-96f56c6984b2.png)

**Comment by manjeshbhargav** [comment]
@mushzak ,

Please take a look at our [Conversations API](https://www.twilio.com/conversations-api). This should help you integrate chat to your application.

Thanks,

Manjesh
