### ISSUE TITLE
Safari Support with iOS 11 and Mac OS High Sierra

### ISSUE THREAD

**Issue by dannycohn** [twilio/video-quickstart-js#19]
With WebRTC Support coming to Safari in iOS 11 and High Sierra, is the Twilio video SDK going to work with Safari?

**Comment by cantyjeffrey** [comment]
+1 to this, would like to start experimenting with this SDK and since iOS 11 is getting more mature, I wanted to check on this as well.

**Comment by kedartoraskar** [comment]
@dannycohn @cantyjeffrey - Experimental Safari 11 support is now available on the Twilio Video JS SDK - https://github.com/twilio/twilio-video.js/issues/122

cc: @markandrus

**Comment by dannycohn** [comment]
I saw this. npm update on the quickstart brought in 1.2.1. Thanks
