### ISSUE TITLE
Local Video Filter Example not working in Chrome

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/video-quickstart-js#196]
Works in 
- Safari Version 14.1.2 (16611.3.10.1.6)  
- Firefox Version 92.0 (64-bit).  

Not working for 
Chrome on Mac Version 93.0.4577.63 (Official Build) (x86_64)

After choosing a filter the Local Video (with filter) displays the gray and white Twilio logo instead of the expected filter video. 

No errors or warnings in the JS Console to report.

**Comment by anthonyjdella** [comment]
Bumping this. 
I was able to reproduce the same issue in Chrome, but it worked for me in Firefox.

**Comment by stevef51** [comment]
Not sure why this is "completed" it is still an issue in Chrome, Firefox, Safari on OSX Ventura
