### ISSUE TITLE
Video Track Manual Controls Example Failing

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/video-quickstart-js#197]
Example fails in all three browsers.

Not working in:
Safari Version 14.1.2 (16611.3.10.1.6)
Firefox Version 92.0 (64-bit).
Chrome on Mac Version 93.0.4577.63 (Official Build) (x86_64)

Safari Console:

[Error] TypeError: null is not an object (evaluating 'track.setContentPreferences')
	setRenderDimensions (index.js:48)
	(anonymous function) (index.js:164)
[Error] TypeError: null is not an object (evaluating 'track.switchOn')
	switchOn (index.js:29)
	(anonymous function) (index.js:147)
[Error] TypeError: null is not an object (evaluating 'track.switchOff')
	switchOff (index.js:38)
	(anonymous function) (index.js:152)

**Comment by makarandp0** [comment]
Hello @spalmertwilio, 

Which version of SDK are you using? Can you post the code that produces these errors?  Is the `track` referenced in the logs a [RemoteVideoTrack](https://media.twiliocdn.com/sdk/js/video/releases/2.16.0/docs/RemoteVideoTrack.html) ? Note that RemoteAudioTrack or RemoteDataTrack does not have these methods available.

Thanks,
Makarand

**Comment by makarandp0** [comment]
@spalmertwilio, never mind my comment - Just realized that you are talking about the quick-start example itself. maybe @PikaJoyce can take a look.

**Comment by PikaJoyce** [comment]
@makarandp0 Can do.

@spalmertwilio do you mind creating some tickets of what you're seeing and I can start working on investigating them?
