### ISSUE TITLE
Voice issue in ios devices

### ISSUE THREAD

**Issue by nitin-619** [twilio/video-quickstart-js#207]
hello @manjeshbhargav , @PikaJoyce , @philnash   we have implemented this library but getting sound issue into ios devices like we have tested in iphone 11, iphone 11 pro , iphone 13, And in iphone 8 and 5s its working, We are also getting issue using //sdk.twilio.com/js/video/releases/2.17.1/twilio-video.min.js javascript sdk in our application, So try to implemented this demo to test voice but still getting same issue,

[Calling Images](https://user-images.githubusercontent.com/94530797/145209182-7ad695d1-d1cc-4bd1-aa40-126e7f977759.png)

**Comment by philnash** [comment]
Hi @nitin-619, it would be helpful if you could explain the sound issues that you are getting. Thanks!

**Comment by nitin-619** [comment]
Hello @philnash  We getting to much slow voice in  iphone 11,iphone 11 pro and iphone 13's speaker  comparison  to android device and iphone 8 and iphone 5s what we have tested into,   Please try to implement this repo from your side too
Note: we have only tested on above devices , It may also occurred into others

**Comment by PikaJoyce** [comment]
Hi @nitin-619,

Thank you for reporting this issue. It sounds like you may be hitting [this issue](https://github.com/twilio/twilio-video.js/issues/1586). Can you please confirm your iOS versions? 

Thanks!
Joyce
