### ISSUE TITLE
Error 53200: Participant identity is invalid

### ISSUE THREAD

**Issue by segheysens** [twilio/video-quickstart-js#21]
I'm generating an Access Token, returning it to my client side, then trying to connect to a room. On the back end, where I create the token and Video grant, I do assign the token an identity property:

```
const token = new AccessToken(
    <account sid variable>,
    <api key variable>,
    <api secret variable>
  );

  token.identity = identity;
  console.log("Identity used: "+token.identity);

  // Grant the access token Twilio Video capabilities, but limit to
  // the room for that lessonID
  const videoGrant = new VideoGrant({
    room: room
  });
  token.addGrant(videoGrant);

  // Serialize the token to a JWT string
  return token.toJwt();
```

The payload of the jwt for the access token looks like this:

```
{
  "jti": "SKe25dcf74ae5c6d14ec20df396e9a43ab-1503603118",
  "grants": {
    "video": {
      "room": "599374468247e824e297ba6d"
    }
  },
  "iat": 1503603118,
  "exp": 1503606718,
  "iss": "SKe25dcf74ae5c6d14ec20df396e9a43ab",
  "sub": "AC79ed9cfda81a51b8005ca41263813b94"
}
```

I noticed [this issue](https://github.com/twilio/video-quickstart-js/issues/8) was referring to virtually the same problem, but I am following the instructions recommended in that post, and don't notice the identity anywhere in the jwt. Any ideas @markandrus ?

**Comment by markandrus** [comment]
Can you please share the version of the helper library you are using, and can you please confirm the identity string is non-empty? The payload you posted is missing an `identity` property, which is why you are getting the error. I'm just not sure why it's missing…

**Comment by segheysens** [comment]
The identity string is "599312b1c0ca871ccc8a9577", it's just a UUID for a test user

**Comment by segheysens** [comment]
I noticed in [the examples](https://www.twilio.com/docs/api/video/user-identity-access-tokens) that the Javascript AccessToken function call is the only language that doesn't include the identity as a parameter - is that correct?

For example...
PHP: ``` $token = new AccessToken($twilioAccountSid, $twilioApiKey, $twilioApiSecret, 3600, $identity); ```
Python: token = ``` AccessToken(account_sid, api_key, api_secret, identity=identity) ```
Ruby: ``` token = Twilio::JWT::AccessToken.new(account_sid, api_key, api_secret, identity); ```
Java (makes another identity function call, it looks like?):
```
AccessToken token = new AccessToken.Builder(
      twilioAccountSid,
      twilioApiKey,
      twilioApiSecret
    ).identity(identity).grant(grant).build();
```

**Comment by markandrus** [comment]
@segheysens thanks for sharing the version of twilio-video.js you use; however, can you please share the version of the helper library you are using? The helper library is the library that actually offers the AccessToken generation APIs (and access to the REST API). For example, the current version of [twilio-node](https://github.com/twilio/twilio-node) is 3.6.4.

As far as the API of the twilio-node helper library, yes I believe you are correct: `identity` can be passed in via `options` or set on the AccessToken instance itself. IMO, it should be a required parameter instead of a member of `options`, since I don't think it is optional... I'll raise this on the twilio-node GitHub issues.

**Comment by markandrus** [comment]
@segheysens I've tried your code for myself (with a few tweaks to set the `identity`, `room`, etc.). It works fine for me. Can you please ensure `identity` is a non-empty string? Here's the output from my terminal session:

```
$ npm install twilio
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ twilio@3.6.4
added 78 packages in 4.793s

$ cat >index.js <<EOF
> const { AccessToken } = require('twilio').jwt
> const { VideoGrant } = AccessToken
> 
> const token = new AccessToken(
>   '<account sid variable>',
>   '<api key variable>',
>   '<api secret variable>'
> );
> 
> token.identity = '599312b1c0ca871ccc8a9577';
> console.log("Identity used: "+token.identity);
> 
> // Grant the access token Twilio Video capabilities, but limit to
> // the room for that lessonID
> const videoGrant = new VideoGrant({
>    room: '599374468247e824e297ba6d'
> });
> token.addGrant(videoGrant);
> 
> // Serialize the token to a JWT string
> console.log(token.toJwt());
> EOF


$ node index.js 
Identity used: 599312b1c0ca871ccc8a9577
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiI8YXBpIGtleSB2YXJpYWJsZT4tMTUwMzY5MDM3NyIsImdyYW50cyI6eyJpZGVudGl0eSI6IjU5OTMxMmIxYzBjYTg3MWNjYzhhOTU3NyIsInZpZGVvIjp7InJvb20iOiI1OTkzNzQ0NjgyNDdlODI0ZTI5N2JhNmQifX0sImlhdCI6MTUwMzY5MDM3NywiZXhwIjoxNTAzNjkzOTc3LCJpc3MiOiI8YXBpIGtleSB2YXJpYWJsZT4iLCJzdWIiOiI8YWNjb3VudCBzaWQgdmFyaWFibGU-In0.4p55numoTLtqkbFIzRr5R18_wXaFzdQKMjXetlWU4DM
```

If I take that Access Token string and paste it into jwt.io, I see the expected payload:

```json
{
  "jti": "<api key variable>-1503690377",
  "grants": {
    "identity": "599312b1c0ca871ccc8a9577",
    "video": {
      "room": "599374468247e824e297ba6d"
    }
  },
  "iat": 1503690377,
  "exp": 1503693977,
  "iss": "<api key variable>",
  "sub": "<account sid variable>"
}
```

Can you please try this out?

Thanks,
Mark

**Comment by segheysens** [comment]
Hi Mark, thank you so much for your help - feel free to close this issue. I was making a mistake, my `identity` variable was an object instead of a string. Thank you so much for your help!

**Comment by segheysens** [comment]
Mistakenly passed object instead of string to AccessToken method.

**Comment by randallb** [comment]
FYI for anyone who stumbles across this: The identity needs to be a string and not a number. If you use a number, it will fail.

**Comment by cluskinator** [comment]
> FYI for anyone who stumbles across this: The identity needs to be a string and not a number. If you use a number, it will fail.

I did - and thank you!  Had been using a random number and got this error.
