### ISSUE TITLE
Cannot create room errors

### ISSUE THREAD

**Issue by michal-blinderhq** [twilio/video-quickstart-js#215]
Hi,

I'm getting repeated "Unable to create Room" errors when trying to create a video room. I have tested this in Chrome and Firefox and I'm getting the same results. My environment details are:

- Windows 11
- Chrome Version 107.0.5304.107 (Official Build) (64-bit)
- Firefox 106.0 (64-bit)

The UI fails with the following error message:
![Screenshot 2022-11-16 133822](https://user-images.githubusercontent.com/92360286/202183901-11706506-18a5-46f1-a053-093d38df13a1.png)

And I'm getting the following error in the console:
`2022-11-16T12:40:22.673Z info [connect #2] Error while connecting to a Room: TwilioError: Unable to create Room
    at RoomCreateFailedError.TwilioError [as constructor] (index.js:26082:27)
    at new RoomCreateFailedError (index.js:25333:28)
    at createTwilioError (index.js:25033:38)
    at TwilioConnection.handleMessage (index.js:17924:34)
    at TwilioConnection.emit (index.js:154:5)
    at TwilioConnection._handleMessage (index.js:20879:14)
    at WebSocket.<anonymous> (index.js:20760:27)`

It also appears that there is some issue with the signalling WSS endpoint. I'm getting this warning a few lines above:
![Screenshot 2022-11-16 134634](https://user-images.githubusercontent.com/92360286/202184346-bdadd892-1101-472b-9e73-4a2c0810f7b8.png)

Thanks

Michal

**Comment by MjCodingCamp** [comment]
Yes, I'm also getting the same error while trying to join room.
