### ISSUE TITLE
Implementation on Twilio Opencv Python

### ISSUE THREAD

**Issue by joviyal-arun** [twilio/video-quickstart-js#217]
its is possible to stream the twilio room with participant and process the stream using python with opencv

**Comment by seancoleman2** [comment]
Hi @joviyal-arun, if you want to process the media after the call ends (not in real-time), you could use our recordings API and then process the raw files afterwards. 

If you want to do some computer vision things in real-time, maybe these blogs would be a good starting point: 

- https://www.twilio.com/blog/christmas-face-masks-twilio-video-tensorflow-webgl 
- https://www.twilio.com/blog/object-detection-serverless-video-tensorflow-js
