### ISSUE TITLE
Doesn't work with Safari 11

### ISSUE THREAD

**Issue by arturitu** [twilio/video-quickstart-js#26]
I have Safari 11 updated (Version 11.0 (12604.1.38.1.7)), but the basic quickstart example doesn't work. It works the same sample project with Chrome, Firefox and between them, but using Safari can not connect. 
![image](https://user-images.githubusercontent.com/5744112/30868385-c2096fb4-a2de-11e7-8a78-4777e63d34fa.png)

**Comment by markandrus** [comment]
Hi @arturitu,

If you test from localhost, you’ll need to enable Develop > WebRTC > Allow Media Capture on Insecure Sites. We should add this to the QuickStart README.md. On HTTPS-enabled sites this is not a problem.

Can you try again with that enabled?

Thanks,
Mark

**Comment by arturitu** [comment]
I just enabled 'Allow Media Capture on Insecure Sites' and now I don't have the previous error, but I can't joined the room, this seems to be similar to what happens in my project where I use Twilio Video that when I call Video.connect, the promise I don't get any response in Safari. For this reason I tested this quickstart too, because was impossible to make it work neither.
![image](https://user-images.githubusercontent.com/5744112/30869792-5ef7b06c-a2e2-11e7-9cbc-d927bcf38c66.png)

**Comment by markandrus** [comment]
@arturitu twilio-video.js does not work with Group Rooms, only P2P for now. Can you please ensure you have set the defaults for your account to "Peer-to-peer"? Please see the screenshot of the Twilio Console below:

![image](https://user-images.githubusercontent.com/359154/30874068-1fdc6eba-a2a4-11e7-871f-4547ab594e4c.png)

**Comment by arturitu** [comment]
Yes, with this change the quickstart project works ok between Safari and Chrome(Mac) of Firefox (Mac).

But on my Twilio project:
- When I use room type "Group":
	It works ok between Chrome (Mac/Windows), Firefox (Mac/Windows), Chrome on Android and all their combinations.
	And doesn’t work on Safari 11 (seems to doesn’t receive a response the promise when you try Video.connect) as expected.
- If I change to room type "Peer-to-Peer":
	On safari 11 emit the video signal to the others but doesn’t render ok its own video signal, and doesn’t render any video received from other browsers.
	On the other browsers some combination stop to work, for example emit video from Chrome Android doesn’t be rendered ok in the rest of the browsers.

And a last question, Is it possible to use different room settings on each API Key? To make tests without breaking nothing that works with room type Group.

**Comment by korasoftware** [comment]
I am having a similar issue trying to connect to a room from Iphone with iOS 11 and Safari, using twilio-video.js - I am not getting any error, it just doesn't connect. I can see local captured video track on iphone, but in Group Mode, iphone won't connect to room. In P2P mode iphone does connect, but sometimes only with audio and no video image. Our requirement is to be able to stream video from iphone to browser and also record the session, but I understand that recording is only possible in group mode. 

Is twilio-video.js likely to be able to allow iphones to connect to a room in group mode, and also record? Is this planned for a future release?

**Comment by markandrus** [comment]
Hi @arturitu,

> ...doesn’t work on Safari 11 (seems to doesn’t receive a response the promise when you try Video.connect) as expected...

Sorry about this. This was indeed a bug we had, and it took us a little while to fix it. The issue is that Safari only supports H.264—not VP8—and so, if you tried to connect to a Group Room (defaults to VP8) from Safari, the Promise never resolved.

Now, the Promise will resolve, and you'll get a new event, ["trackPublicationFailed"](http://media.twiliocdn.com/sdk/js/video/releases/1.6.0/docs/LocalParticipant.html#event:trackPublicationFailed), describing what happened. For example,

```js
connect(token).then(room => {
  room.localParticipant.on('trackPublicationFailed', (error, localTrack) => {
    console.log('Failed to publish LocalTrack %s:', localTrack.id)
    console.log(error.message)
    // => Failed to publish LocalTrack XXX:
    // => No supported codec
  })
})
```

Although Safari will be unable to send or receive video in such a Room, audio will still work. We're actively working on improving the Group Room experience with Safari Participants.

> On safari 11 emit the video signal to the others but doesn’t render ok its own video signal, and doesn’t render any video received from other browsers.

This is odd. Are you still experiencing this? We did patch some behavior for iOS that would ensure videos played back.

> And a last question, Is it possible to use different room settings on each API Key? To make tests without breaking nothing that works with room type Group.

Unfortunately not. Since the default Room settings are account-level, you could either create two accounts (or sub-accounts); or you could use the REST API to pre-create the Rooms (in which case you can choose the type, among other things). See [here](https://www.twilio.com/docs/api/video/rooms-resource) for more info.

Best,
Mark

**Comment by markandrus** [comment]
@korasoftware 

> I am not getting any error, it just doesn't connect. I can see local captured video track on iphone, but in Group Mode, iphone won't connect to room. In P2P mode iphone does connect, but sometimes only with audio and no video image.

Can you confirm what version of twilio-video.js you are using?

> Is twilio-video.js likely to be able to allow iphones to connect to a room in group mode, and also record? Is this planned for a future release?

Yes, this is planned. We may call it "multi-codec support for Group Rooms", or something similar.

Best,
Mark

**Comment by inkredabull** [comment]
Cross-referencing: 
https://github.com/twilio/video-quickstart-js/issues/26
