### ISSUE TITLE
Question re: deployment on Azure or Heroku

### ISSUE THREAD

**Issue by kabhatta** [twilio/video-quickstart-js#28]
Hi there, has anyone tried or successfully deployed this on a cloud (e.g. Azure or Heroku, which is what I have tried?). I admit that I am not an expert with Node at all, so learning through the fire hose right now. But the issue seems to be with the build of npm-run-clean 
2017-10-14T09:41:57.264888+00:00 app[web.1]: > npm-run-all clean:*
2017-10-14T09:41:57.264889+00:00 app[web.1]: 
2017-10-14T09:41:57.270239+00:00 app[web.1]: sh: 1: npm-run-all: not found
2017-10-14T09:41:57.274248+00:00 app[web.1]: 
2017-10-14T09:41:57.281360+00:00 app[web.1]: npm ERR! Linux 3.13.0-128-generic
2017-10-14T09:41:57.281564+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "run" "clean"

Any pointers would be appreciated. I'm raising it here simply out of ignorance as I am not sure if I am doing the wrong thing or if this is by design. 
Thanks

**Comment by markandrus** [comment]
Hi @kabhatta,

Perhaps you are getting

```
2017-10-14T09:41:57.270239+00:00 app[web.1]: sh: 1: npm-run-all: not found
```

Because you haven't run

```
$ npm install
```

yet? This should install the command `npm-run-all` and allow you to run it. If you share a bit more about how you setup the application, perhaps I could help.

Best,
Mark

**Comment by Maxeeeeeeeeem** [comment]
Adding `"heroku-prebuild"` & `"heroku-postbuild"` to my `"scripts"` in my `package.json` allowed Heroku to properly install `npm-run-all` during build and successfully launch the server.

```
"scripts": {
    "heroku-prebuild": "export NPM_CONFIG_PRODUCTION=false; export NODE_ENV=; NPM_CONFIG_PRODUCTION=false NODE_ENV=development npm install --only=dev --dev",
    "heroku-postbuild": "export NPM_CONFIG_PRODUCTION=true; export NODE_ENV=production;"
  },
```

Source: @josecelano [unable to deploy to heroku](https://github.com/react-boilerplate/react-boilerplate/issues/1818#issuecomment-350271686)

**Comment by seanfcarroll** [comment]
@Maxeeeeeeeeem if this is resolved could you please close the issue?
