### ISSUE TITLE
Cannot connect to twilio from andriod chrome web view , error:Signaling connection disconnected when trying to connect to room 

### ISSUE THREAD

**Issue by soorya02** [twilio/video-quickstart-js#30]
Hi Team,
There is an issue while connecting to room , I got the error 53000, signaling connection disconnected when trying to connect to room.  But it was working fine till yesterday. Any suggestions?

**Comment by pnrtkr** [comment]
I was getting 53000 signalling connection error because of the conflict with one of my other libraries using websocket. I suggest checking dev tools -> network -> initiator all fun happening in the twilio-video.js

**Comment by markandrus** [comment]
Hi @soorya02,

We run end-to-end testers continuously and haven't noticed any degradation of service. Has anything changed with your application or the environment you use/test your application from in the meantime? Any chance you are using a newer version of Chrome? Mind sharing you versions and log output?

Thanks,
Mark

**Comment by markandrus** [comment]
@soorya02 I will close this issue since there hasn't been any activity in a while. If you continue to experience this issue, could you please re-open the ticket on [twilio/twilio-video.js](https://github.com/twilio/twilio-video.js)? Thanks, Mark
