### ISSUE TITLE
Full-res Recording Capability

### ISSUE THREAD

**Issue by cdstamper** [twilio/video-quickstart-js#31]
Is there capability to record the source video stream at full quality, without subjecting the recording to network-related quality degradation? Maybe a client side recording at full res, uploaded non-real-time?

**Comment by markandrus** [comment]
Hi @cdstamper. Client-side recording might be the best option here. You could either record client-side, then upload the full recording at the end of the video chat, or perhaps chunk up the recording and stream the chunks up to a server. These would be solutions outside of Twilio's server-side APIs.

Would it be useful if we added a client-side example to this repo?

Thanks,
Mark

**Comment by swift2geek** [comment]
Hy guys, 
im trying to rec video locally on ios device but cant understand how i can infiltrate in twilio's localVideoTrack and intercept it to save it locally on ios device. I didnt find anything on stackoverflow. Any suggestions would be appreciated.

**Comment by markandrus** [comment]
Hi @swift2geek,

You can always get the MediaStreamTrack inside of some LocalAudioTrack, LocalVideoTrack, RemoteAudioTrack, or RemoteVideoTrack—call it `track`—by accessing the following:

```js
track.mediaStreamTrack
```

Often times, browser APIs want a MediaStreamTrack packaged up inside of a MediaStream. You can do this by constructing a new MediaStream and calling `addTrack`:

```js
const mediaStream = new MediaStream()
mediaStream.addTrack(track.mediaStreamTrack)
```

With this, you should be able to use the [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API) to implement client-side recording.

**Comment by markandrus** [comment]
Sorry, accidentally closed the issue. Please let me know if that helps.

**Comment by swift2geek** [comment]
@markandrus finally i was able to write video locally. Thanks for help
