### ISSUE TITLE
Stitching video recording back together

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-js#32]
We have been using the room recording feature and now would like to go back and look at recordings.  However, we aren't sure how to piece them back together into something that can be watched.

As far as we can tell, each participant is recorded into two files, one for video (VP8) and one audio (opus).  It is straightforward to combine these with ffmpeg into a webm file.

Combining participants seems possible with ffmpeg and a filter to place the streams side-by-side.

However, there seem to be separate pairs of files for each time a participant joins/leaves?  Plus it isn't clear how to synchronize any of the participants together?

I am confused as to how anyone could use these recordings in their current form?

This may be somewhat related to #31 as a client side recording might do this, but then what is the recording feature for?

**Comment by mcorner** [comment]
Just found this: https://github.com/twilio/twilio-video.js/issues/187

**Comment by markandrus** [comment]
Hi @mcorner,

I'll close this for now, since I think there's been more discussion on the issue you linked.

Best,
Mark
