### ISSUE TITLE
Documentation is wrong!!

### ISSUE THREAD

**Issue by cipriancaba** [twilio/video-quickstart-js#34]
Huys, I just spent one hour trying to figure out what the hell is going on, following the official instructions from https://www.twilio.com/docs/api/video/javascript-v1-getting-started

```
// Attach the Participant's Media to a <div> element.
room.on('participantConnected', function(participant) {
  console.log("Participant '" +  participant.identity  + "' connected");

  participant.tracks.forEach(track => {
    document.getElementById('remote-media-div').appendChild(track.attach());
  });
});
```

This is not working, because the tracks are empty at that moment, you need to wait for trackAdded event.. Please update the docs, this is really not cool

**Comment by markandrus** [comment]
Hi @cipriancaba,

I'm really sorry you had trouble, but I'm glad you were able to find the fix. You do have to wait for the "trackAdded" event. I've just opened a PR against our docs repo with this clarification.

Mark

**Comment by jhovad** [comment]
Is this still something I have to handle in 2x API ? There is no "trackSubscribed" event listener in quickstart code ...
