### ISSUE TITLE
how to create a configuration file 

### ISSUE THREAD

**Issue by mkmdisticaret** [twilio/video-quickstart-js#35]
I am newbie node.I want to use the this.But i do not know how to create configuration file.Node server throw exception du to lack of SID.But i do not know how write it.

**Comment by markandrus** [comment]
Hi @mkmdisticaret,

Do you have all the necessary values?

* `TWILIO_ACCOUNT_SID`
* `TWILIO_API_KEY`
* `TWILIO_API_SECRET`

These three values can be gathered or created from the Twilio Console. For example, you can get the Account SID from here:

<img width="991" alt="screen shot 2017-12-22 at 9 45 53 am" src="https://user-images.githubusercontent.com/359154/34307434-f0869a30-e6fc-11e7-81c7-f5abdcba106e.png">

Then, in the Twilio Console, you can create the API Key and get the API Key Secret by clicking on "Programmable Video" → "Tools" → "API Keys" → "Create a new API Key". Then, create a Standard API Key. You can name it whatever you'd like:

![create-an-api-key](https://user-images.githubusercontent.com/359154/34307472-2bbcbb66-e6fd-11e7-999c-b8728078a5b5.png)

When you create the API Key, you have one chance to record the secret.

![api-key](https://user-images.githubusercontent.com/359154/34307495-4624e820-e6fd-11e7-8636-79bbc97712b4.png)

Once you have these three files, you'll want to create a file named `.env` in the root of this project. You can use any text editor you like. The file contents should look like `.env.template`, i.e.

```
TWILIO_ACCOUNT_SID=ACxxxxxxxxxx
TWILIO_API_KEY=SKxxxxxxxxxx
TWILIO_API_SECRET=xxxxxxxxxx
```

except you should replace the values to the right of the "=" with the actual values you gathered from the Twilio Console.

Can you please try this?

Thanks,
Mark

**Comment by kimobrian** [comment]
@markandrus So I followed the steps in the documentation which are the same as yours but under the `Project Info` in the screenshot above I clicked on Project settings and picked the `TEST ACCOUNT SID` from the next page. Though I also tried the `ACCOUNT SID` on the dashboard. I get an error whose code does not even occur on [this page](https://www.twilio.com/docs/api/client/errors). I am working on localhost with the video-quickstart.js. Is there something else I am supposed to configure.

![image](https://user-images.githubusercontent.com/22055697/35174831-d9cfc2da-fd81-11e7-81c7-00d6820cf232.png)

**Comment by markandrus** [comment]
Hi @kimobrian,

> @markandrus So I followed the steps in the documentation which are the same as yours but under the `Project Info` in the screenshot above I clicked on Project settings and picked the `TEST ACCOUNT SID` from the next page.

I don't think Twilio Video supports Test Account credentials. Please use the normal Account credentials.

> I get an error whose code does not even occur on [this page](https://www.twilio.com/docs/api/client/errors).

That page documents Twilio Client errors, e.g., for twilio.js. It does not document Twilio Video errors, e.g., for twilio-video.js. The full [Error and Warning Dictionary](https://www.twilio.com/docs/api/errors) includes an entry for [Error 21051](https://www.twilio.com/docs/api/errors/20151).

> I am working on localhost with the video-quickstart.js. Is there something else I am supposed to configure.

No there is nothing else to configure. Please ensure you've setup `.env` with the normal Account credentials as described above and not the Test Account credentials. Please also ensure you have copied the API Key Secret correctly. This is distinct from the Auth Token and the part that trips many people up. It's also only shown once when you create the API Key. The API Key SID, which you also need, starts with "SK".

> If I am not wrong, the app is supposed to automatically generate a token. It actually worked once then every subsequent time I get this.

Yes, the app will generate an Access Token based on the contents of `.env`. Please ensure you aren't overriding the same environment variables declared in `.env` when running the quickstart application.

Mark

**Comment by kimobrian** [comment]
@markandrus Still getting the error above even after the changing the account SID

**Comment by kimobrian** [comment]
I also checked the token with jwt.io and it results to invalid signature:

![image](https://user-images.githubusercontent.com/22055697/35183339-6a1b7b0e-fdf5-11e7-834f-263a1075b80f.png)

**Comment by kimobrian** [comment]
@markandrus Managed to solve it. I had another account sid in my bash_profile from a previous project which was overriding my current one in .env. Thanks for the help though.

**Comment by adarshponaka** [comment]
I am having the same issue. Are you sure I need a normal, not trial, twilio account? their website says there are no limitations for twilio video, and I don't want to spend $20 to upgrade my account if I do not need to. Thanks! )(btw I my bash_profile has nothing in it, so that can't be the same issue for me) Thanks
