### ISSUE TITLE
No video preview

### ISSUE THREAD

**Issue by grantspilsbury** [twilio/video-quickstart-js#38]
If I add the env variables, run npm install, run npm start (I see in terminal that some files are being copied, and the message saying the express server is running on *:3000), and go to http://localhost:3000 clicking the preview camera button doesn't display any video in the preview video block. I click on the button and nothing gets logged to console or to terminal. I'm able to join / create rooms but there's no video. Any idea what could be the issue? I am on a mac, using chrome, and am working on the javascript video quickstart repo on github.

**Comment by markandrus** [comment]
Hey, @grantspilsbury -- any chance you have an adblocker or something running? or a WebRTC blocker? Do you have an audio/video device on your computer? Also, what version of Chrome? Maybe if you could post a screenshot, that would help.
