### ISSUE TITLE
Twilio Still not turning off camera on disconnect

### ISSUE THREAD

**Issue by rohitbegani** [twilio/video-quickstart-js#40]
Disconnecting a call doesn't remove the tracks and the camera still stays on. I'm in the development mode on Mac OS High Sierra v 10.13.3 and Chrome Version 64.0.3282.186. 

My React function to disconnect the call is:

```javascript
disconnectCall() {
    let { currentRoom } = this.state;
    console.log("The current room is", currentRoom);
    if (currentRoom != null) {
      this.token = null;
      this.setState({ tracks: {counterparty: {}, local: []}, disconnected: true });
      currentRoom.disconnect();
    }
}
```

The console log gives me all the proper information about the room so ideally, it should work.  But it doesn't seem to be doing anything and the second `console.log` gives me the same room information including the tracks for the localParticipant. From what I understand these should be removed by calling disconnect right? Please let me know if there's something wrong with my understanding or if I need to take an additional step to disconnect the camera.

**Comment by markandrus** [comment]
Hi @rohitbegani,

Can you please share your code for connecting to the Room? If you pass LocalTracks into `connect` like

```js
connect(token, { name: 'my-room', tracks })
```

then you "own" the lifecycle of the LocalTracks, i.e., you need to call `stop` on each with

```js
tracks.forEach(track => track.stop())
```

when you're done with them, i.e., after disconnected from the Room. If you don't provide LocalTracks to connect, i.e., you call

```js
connect(token, { name: 'my-room' })
```

then `connect` acquires a "default" LocalAudioTrack and LocalVideoTrack and it will manage the lifecycle of these LocalTracks for you and disconnecting from the Room will automatically `stop` them.

Does that make sense?

Thanks,
Mark

**Comment by rohitbegani** [comment]
@markandrus thank you for the quick response. That does make sense, and you're right I passed the `tracks` while connecting to the room. So following your response I updated the if case as:

```javascript
if (currentRoom != null) {
      this.token = null;
      this.setState({ tracks: {counterparty: {}, local: []}, disconnected: true });
      currentRoom.disconnect();
      currentRoom.localParticipant.tracks.forEach(track => track.stop());
}
```

But it still isn't turning off the camera. I'm wondering if there is something extra I need to do in case of React; like update a `state` but that shouldn't be the case because this is a change on the browser

**Comment by markandrus** [comment]
@rohitbegani NP, you're welcome. Please check to see if you call `createLocalVideoTrack` or `createLocalTracks` anywhere else in the code. The camera light will remain on so long as there is an unstopped MediaStreamTrack in the page (the LocalAudioTrack and LocalVideoTracks are just wrappers around MediaStreamTracks). There's nothing special you need to do for React.

If you aren't sure how many LocalVideoTracks are being created and stopped in the page, you can set `{ logLevel: 'debug' }` in each of `connect`, `createLocalTracks`, and `createLocalVideoTrack`, e.g.

```
// 1
connect(token, { logLevel: 'debug' })

// 2
createLocalTracks({ logLevel: 'debug', video: true })

// 3
createLocalVideoTrack({ logLevel: 'debug' });
```

For each line that looks like

```
2018-03-01 23:17:32.143Z | DEBUG in [LocalVideoTrack #1: 1053e62e-6ac2-406a-bf35-ea684fa693c0]: Initializing
```

You should eventually see a line like

```
2018-03-01 23:17:34.462Z | INFO in [LocalVideoTrack #1: 1053e62e-6ac2-406a-bf35-ea684fa693c0]: Stopping
```

For example:

![image](https://user-images.githubusercontent.com/359154/36875201-d8d9a75e-1d63-11e8-94e6-38fcc78c38a5.png)

If you see any unmatched pairs of "Initializing" and "Stopping", then you have a "leaked" track.

**Comment by rohitbegani** [comment]
I only have one `createLocalTracks` in the connect function.

```javascript

  connectToTwilio(token, roomName) {
    this.token = token;
    Video.createLocalTracks( {logLevel: 'debug'} ).then((localTrack) => {
      this.localTrack = localTrack;
      Video
        .connect(token, { name: roomName, track: localTrack, logLevel: 'debug' })
        .then(room => {
          this.setState((prevState) => {return { ...prevState, currentRoom: room } });
          this.iterateLocalParticipantTracks(room.localParticipant);
          room.participants.forEach(this.participantConnected);
          room.on('participantConnected', this.participantConnected);
          room.on('participantDisconnected', this.participantDisconnected);
          room.once('disconnected', error => room.participants.forEach(this.participantDisconnected));
        }, (err) => {
          this.showTwilioError();
        });
    }, () => {
      this.showTwilioError();
    });
  }
```

The `loglevel: 'debug'` was very helpful though. I think I understand why this issue is coming up. For some reason, I seem to have 2 copies of both the `VideoTracks` and the `AudioTracks` and only one of them gets stopped for both of them. I'm wondering if the duplicate is because of the `remote participant`, I'll update this thread when I figure out the issue

<img width="660" alt="screen shot 2018-03-05 at 1 44 55 pm" src="https://user-images.githubusercontent.com/4975966/36993506-037f589e-207c-11e8-84b7-c992e6b95da5.png">
Two copies of both audio and video track.

<img width="659" alt="screen shot 2018-03-05 at 1 46 51 pm" src="https://user-images.githubusercontent.com/4975966/36993533-1a775e52-207c-11e8-81ee-05c06ad899d2.png">
The duplicate gets stopped.

**Comment by markandrus** [comment]
@rohitbegani I believe the issue is here:

```js
.connect(token, { name: roomName, track: localTrack, logLevel: 'debug' })
```

`track` should be `tracks` (check out the [ConnectOptions](https://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/global.html#ConnectOptions) API for more details). Since `tracks` is not provided to `connect`, it assumes you want it to automatically acquire a default LocalAudioTrack and LocalVideoTrack. These automatically acquired LocalTracks will be stopped when you `disconnect` from the Room. (If you pass LocalTracks in yourself via `tracks`, you must `stop` them yourself).

**Comment by rohitbegani** [comment]
@markandrus Yes sir! You're absolutely correct. I assumed that that was a state issue. Really appreciate your help on this
