### ISSUE TITLE
Rails quickstart

### ISSUE THREAD

**Issue by jdrnd** [twilio/video-quickstart-js#42]
I'm working on porting the backend here to Rails for work. Would the maintainers be interested in adopting a minimal version of it for open usage? I'd be willing to put in a few hours of dev time cleaning it up and making sure it's up to any relevant code standards.

**Comment by seanfcarroll** [comment]
I'd love to see this.

**Comment by seanfcarroll** [comment]
Bit of a shame there was no response from Twilio when a community member is offering to code a useful quickstart repo. Digital Ocean pay contributers for this kind of content.

**Comment by shoaib-iqbal** [comment]
For rails I have integrated multiparty Video call
[Rails Twilio Video Quick Start](https://github.com/shoaib-iqbal/twillio-quick-start-rails)
