### ISSUE TITLE
Recording Remote Video

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-js#43]
We would like to record both sides of video call.  We would use group rooms, but we ran into a show stopping bug: https://github.com/twilio/video-quickstart-android/issues/266

It also seems like p2p connections have much higher quality and reliability.

There is one previous issue that shows how to record local video: #31 
 
But it seems like it only works for local videos.  For instance, if we do this for a remote video track I get a video with 0 length (though it seems to show one frame of the video?).  This snippet below is inside of a react app, but you get the idea.

Do you know how to record remote tracks in the browser?  

Thanks! 

```
static startRecording(track){
    if (track.kind=="audio") {
      return;
    }

    const mediaStream = new MediaStream();
    mediaStream.addTrack(track.mediaStreamTrack);
    this.recorder = new MediaRecorder(mediaStream);

    this.recordedBlobs = [];

    this.recorder.addEventListener('dataavailable', (e) => {
      // e.data
      console.log("recorder got blob :" + e.data.size);
      if (e.data.size > 0){
        this.recordedBlobs.push(e.data);
      }
    });

    this.recorder.addEventListener('stop', (e) => {
      console.log('recorder onstop');

      console.log("Have blobs: " + this.recordedBlobs.length);
      var blob = new Blob(this.recordedBlobs, {mimeType: 'video/webm'});
      this.recordedVideo = URL.createObjectURL(blob);
      console.log(this.recordedVideo);
    });

    console.log("Start recording");
    this.recorder.start(1000);

    setTimeout(() => {console.log("Stop recorder"); this.recorder.stop()}, 5000);
  }
```

**Comment by AkshayBarad** [comment]
Hi @mcorner, were you able to find a solution?

**Comment by mcorner** [comment]
No we are using a screen capturing extension for Chrome (screencastify) to accomplish this.

**Comment by markandrus** [comment]
Hey @AkshayBarad and @mcorner,

I believe this is due to Chromium [Issue 760760](https://bugs.chromium.org/p/chromium/issues/detail?id=760760). I recently hit this myself. It seems like, for remote video, Chromium's MediaRecorder implementation won't capture additional frames beyond the one or two you see _unless_ there's some kind of active audio MediaStreamTrack paired with it. So here's the workaround I found: use the Web Audio API to construct a "dummy" audio MediaStreamTrack. It doesn't seem to be enough to just create a MediaStreamDestinationNode, though—you need to pump audio samples through it—so I connect an OscillatorNode with `frequency` zero.

Riffing on your code above, you could have something like the following:

```js
const mediaStream = new MediaStream();
mediaStream.addTrack(track.mediaStreamTrack);

if (track.kind === 'video') {
  // NOTE: This is a hack to workaround the following bug:
  //
  //  https://bugs.chromium.org/p/chromium/issues/detail?id=760760
  //
  const audioContext = new AudioContext();
  const destinationNode = audioContext.createMediaStreamDestination();
  const oscillatorNode = audioContext.createOscillator();
  oscillatorNode.frequency.setValueAtTime(0, audioContext.currentTime);
  oscillatorNode.connect(destinationNode);
  const [audioTrack] = destinationNode.stream.getAudioTracks();
  mediaStream.addTrack(audioTrack);
}

this.recorder = new MediaRecorder(mediaStream);
```

Can you please try this?

Thanks,
Mark

**Comment by AkshayBarad** [comment]
Thanks, @markandrus 🙏 
I will try this and post my results here.

**Comment by AkshayBarad** [comment]
We tried generating 'fake audio' track like in @markandrus 's sample above and were able to circumvent the chrome bug he pointed out. 
In general, we intend to include the remote participants' real audio tracks. We shall use the workaround when there is no audiotrack for a participant.

Many thanks, @markandrus.

**Comment by mcorner** [comment]
Ah this seems to work, though we really didn't need fake audio.   We just didn't start recording until the audio track was available and added them both at the same time.  Thanks!!!

**Comment by mcorner** [comment]
Also, we used this to combine the streams: https://github.com/t-mullen/video-stream-merger (works really well)

**Comment by JamieCorkhill** [comment]
Is this still an issue? I find that I can record my local stream just fine, but not the remote one. The call to `getUserMedia` on the local side passes in `{ audio: false, video: true }` as the sole media stream constraints.

When I open the resulting webm file in VLC, it seems that only 1 frame exists, although the duration is 0 when looking at `ffmpeg`.

Thanks.
