### ISSUE TITLE
Publish videotrack only after joining room

### ISSUE THREAD

**Issue by ppriyank40** [twilio/video-quickstart-js#44]
Hello,
I want to first join the room without adding video track first. And then any participant joins the same room then and then only i want to add video track to that room.
The main goal of this is to save bandwidth of user if call is not connected with someone.

**Comment by smkrn110** [comment]
I think following code you were expecting, at first just publish the audio track after that publish the video track (on condition)

```
First) const track = await Twilio.Video.createLocalAudioTrack();
room.localParticipant.publishTrack(track)

Second) const track = await Twilio.Video.createLocalVideoTrack();
room.localParticipant.publishTrack(track)
```
