### ISSUE TITLE
Uncaught (in promise) DOMException: Requested device not found

### ISSUE THREAD

**Issue by hotmailruteeb** [twilio/video-quickstart-js#49]
I am trying to use video with twilio, 
When I go to video room I get the following message: 
Uncaught (in promise) DOMException: Requested device not found

and there is no video appears.

I tried to install ssl, but I had the same problem.

I searched over internet about a solution, but I did not find article for twiloi.

I am using laravel framework

**Comment by markandrus** [comment]
Hi,

This repo does not use Laravel, it is a Node.js-based Quickstart. For help, I recommend you write to support@twilio.com.

Thanks,
Mark

**Comment by huskar357357** [comment]
Actually, you have a device like Camera.
That error occurs because twilio can not find the device.

**Comment by manjeshbhargav** [comment]
Hi @huskar357357 ,

This error is returned by the browser, not the Twilio Video SDK. So, this means that the browser did not detect your camera.

Thanks,

Manjesh Malavalli
JSDK Team
