### ISSUE TITLE
Camera doesn't work after leaving the room

### ISSUE THREAD

**Issue by tjblanco** [twilio/video-quickstart-js#51]
Hi all,
I have run the app, previewed my camera and joined a room. When I leave the room, then I am not able to preview my camera again and when I join a new room, the camera doesn't work.

**Comment by lmatheus** [comment]
Same behaviour on my part

**Comment by manjeshbhargav** [comment]
Hi @tjblanco , @lmatheus ,

Sorry for the delayed response, and thank you for bringing this behavior to our notice. I will update the QuickStart App with a fix for this soon.

Please watch this space for updates.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@tjblanco , @lmatheus ,

Can you pull in the latest changes from the remote branch you are on? I've added some changes that will fix this issue. Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
