### ISSUE TITLE
Making ScreenShare mode to publish audio from other apps

### ISSUE THREAD

**Issue by rajeefmk** [twilio/video-quickstart-js#54]
Here's the scenario : 
User 1 enables screen share mode. Puts the app in background. Opens up Youtube/any other video player. 
User 2 should be able to listen to both the microphone output of User 1 as well as the output of what's being played by Youtube/video. 

Currently, The User 1's mic output is received successfully by User 1 but the third party app's output is not available. 

Any direction/help on how to go about solve this ? 

Thanks

**Comment by manjeshbhargav** [comment]
Hi @rajeefmk ,

I think you can use the [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) API to capture screen audio and then publish it to the Room. Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team
