### ISSUE TITLE
Composed media URL getting expired

### ISSUE THREAD

**Issue by Glory-Victor** [twilio/video-quickstart-js#57]
While getting the composition media URL we had set the TTL to 7 days but still, the link expires within 6 hours. 

#### Expected Behaviour: 
  URL should be valid for 7 days
#### Current Behaviour:
   URL expires within 6 hours.

**Comment by sonalikatara** [comment]
I am experiencing the same issue, the composition media URL expire earlier than a week, any updates on this?
