### ISSUE TITLE
Serve over HTTPS

### ISSUE THREAD

**Issue by m6246** [twilio/video-quickstart-js#58]
Not sure if this is a special use case but I couldn't find any issues on this so it seems worth noting here.

As getUserMedia is only available from secure contexts and I wanted to test with a client who obviously can't reach localhost, we weren't able to do so. This lead to me changing the server to use https:

```
var fs = require('fs');
var server = require('https').createServer({
    key: fs.readFileSync('/path/to/key.pem'),
    cert: fs.readFileSync('/path/to/cert.pem')
}, app);
var port = process.env.PORT || 3000;
server.listen(port, function() {
  console.log('Express server running on *:' + port);
});
```

Of course this needs a valid SSL-certificate and your server to be publicly visible.

**Comment by manjeshbhargav** [comment]
@m6246 ,

You can also use [ngrok](https://ngrok.com/) to generate public URLs (https as well) for your local development server, which can be accessed from a another machine. Please let me know if this works out for you.

Thanks,

Manjesh Malavalli
JSDK Team
