### ISSUE TITLE
Enable/ Disable other participants audio

### ISSUE THREAD

**Issue by ksaadST** [twilio/video-quickstart-js#64]
How can i enable/disable(mute/unmute) audio of other participants. I have a user case in my application in which i have to mute other participants audio on my end only.
I have used below code: 
allParticipant.audioTracks.forEach(function (audioTrack) {
            if (audioTrack.isEnabled) {
                audioTrack.disable();
            }
        });

audioTrack.disable is not a function i am getting this error.

**Comment by manjeshbhargav** [comment]
Hi @ksaadST ,

I apologize for the delayed response. We don't support muting RemoteParticipants' Tracks at this point. However, you can achieve this in your application as follows: when Alice wants to mute Bob's audio, Alice sends a message through your applications signaling channel to Bob to mute his audio. Then, Bob calls `localAudioTrack.disable()`.

Please let me know if this works for you. I'm going to close this issue since this was mainly a question.
Feel free to open a new issue if you have other questions/concerns.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by elebumm** [comment]
Hey @manjeshbhargav, I am looking for this functionality. Is this something that the DataTracks API can do? Or will I have to find my own solution?

**Comment by pierrenel** [comment]
@elebumm did you figure this out? I'm ... also wondering if DataTracks is the answer.

**Comment by elebumm** [comment]
No @pierrenel I haven't. I am working on implementation this week on my end. So I can get back to you. 

Here is my understanding of DataTracks API though. From what it sounds like, it looks like DataTracks allows you to send messages through the WebSocket connection that the Twilio Video API is already using.

The way you would need to set up the application is so that an "Admin" user only has access to these features. and all the participants have event listeners on them. Once the "muteParticipant" event goes off, you run the code to mute that individual. 

I will investigate and see if DataTracks API will work.

**Comment by elebumm** [comment]
Just posting in here to show my findings. I think I will make a more in detail example later but I was able to complete the functionality I was looking for with DataTracks.

Context - my application requires an admin to enter an "admin code" to show a different user interface that lets them mute and kick other participants. I created a `LocalDataTrack` and connected to the room with the track alongside the mic and video.

In a button I have this onClick method:
```javascript
onClick={(e) => {
                                            e.preventDefault();
                                            localDataTrack.send(
                                              JSON.stringify({
                                                type: "REMOVE_FROM_CALL",
                                                participant: participant,
                                              })
                                            );
                                          }}
```

It takes the `LocalDataTrack` and sends a stringified JSON object. I have this structured similarly to a Redux Action but you can do whatever. 

```javascript
room.on("trackSubscribed", function (track: Track) {
        track.on("message", function (message: any) {
          const messageBody = JSON.parse(message);

          if (messageBody.type === "REMOVE_FROM_CALL") {
            if (
              messageBody.participant.identity ===
              room.localParticipant.identity
            ) {
              room.disconnect();
              history.push("/");
            }
          }
        });
      });
```

Once connected to the room, you setup an Event Listener for `trackSubscribed` and listen for the `message` event on the track. I only have `REMOVE_FROM_CALL` where it uses the `room.disconnect()` method once it matches that `type` and `participant` identity.

Hope this helps. It's very rough in my application at the moment, but the DataTracks API is really showing to be an under rated feature within this product. 👍

**Comment by tamilzh** [comment]
Is there any option that exists to mute the remote participant? I have a use case to mute a remote participant from all participants

**Comment by elebumm** [comment]
@tamilzh There isn't any solution out of the box, but you can use the DataTracks API to push state to the remote user where it will turn off on their end. You would have to implement your own method to authenticate that the user is an admin though. Check my answer above

**Comment by tamilzh** [comment]
@elebumm Thanks for your reply. How can we created a LocalDataTrack to the room with audio and video tracks. If I connect with LocalDataTrack then my video and audio tracks are not connected. I m using the twilio-quickstart-js sample below is the code connect to the room, I just added the content in Bold

 const { connect, createLocalVideoTrack, **LocalDataTrack**  } = require('twilio-video');
 **var dataTracks = new LocalDataTrack();**
  .......
  .......
  .......
  .......
  // Join to the Room with the given AccessToken and ConnectOptions.
  **connectOptions.tracks = [dataTracks];**
  const room = await connect(token, connectOptions);

  let localVideoTrack =  Array.from(room.localParticipant.videoTracks.values())[0].track;

I got an error at localVideoTrack saying Array.form(..)[0] is undefined. If I commented on the localVideoTrack, then it works fine but the video is not coming up.

Any help would be appreciated.

**Comment by elebumm** [comment]
@tamilzh Treat the DataTrack like it's a AudioTrack or VideoTrack. You have to include it within an array in your connect options.

Let's assume that you have these variables in as well:

```
var dataTracks = new LocalDataTrack();
var videoTrack = new LocalVideoTrack();
var audioTrack = new LocalAudioTrack();
```

Then in the connect options, you will need to include all those:

```
connectOptions.tracks = [videoTrack, audioTrack, dataTracks];
const room = await connect(token, connectOptions);
```

Does that work?

**Comment by tamilzh** [comment]
@elebumm It's not working but I can able to do it. Thanks for ur idea about using data tracks much appreciated. Below is the working code 

const { connect, LocalDataTrack, createLocalTracks } = require('twilio-video');
...
...
const dataTrack = new LocalDataTrack();
const audioAndVideoTrack = await createLocalTracks();
const tracks = audioAndVideoTrack.concat(dataTrack);
const name = "Video Chat"
//const room = await video.connect(token, connectOptions);
const room = await connect(token, {
    name,
    tracks
  });

**Comment by elebumm** [comment]
Data Tracks is a pretty powerful feature, just for this use case scenario, you will probably need to roll out your own authentication system that will let people know who the admin is :)
