### ISSUE TITLE
Hi, i am applying "type" property but not working 

### ISSUE THREAD

**Issue by Govind13100** [twilio/video-quickstart-js#69]
Hi, i am trying to join room with "group-small" type, but passing property type:"group-small" doest work, below is my code 

`var connectOptions = {video: videoConstraints, type:'group-small', audio: true, name: roomName, preferredVideoCodecs: ['H264', 'VP8'], networkQuality: true};  `
`Twilio.Video.connect(data.token, connectOptions).then(roomJoined, function(error) {
          console.log('Could not connect to Twilio: ' + error.message);
        });`

**Comment by makarandp0** [comment]
Hey @Govind13100, `type` is not one of the [supported options](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta9/docs/global.html#ConnectOptions) . To create group room you need to configure your room setting in console, and/or use the REST api to create the group-room. You can read more about it [here](https://www.twilio.com/docs/video/javascript-v2-getting-started#default-room-settings).
