### ISSUE TITLE
record video calls on demand

### ISSUE THREAD

**Issue by umesh-lnt** [twilio/video-quickstart-js#75]
We want to be able to record video calls in a particular room only when the user wants to record the video.
Currently the recording starts as soon as the the participant joins (RecordParticipantsOnConnect set to true). However we want it to be user controlled, maybe by calling an API with the push of a button.
Can you please guide me on this one?

**Comment by mark-beeby** [comment]
I'm looking at this, it seems as you say like it's an all or nothing affair within rooms. There's only two options I can think:-

- Record it all, capture the timestamp from the recording start / stop calls, slice the resulting video composited video file accordingly.
- Move everyone to a new room (with the config enabled) upon clicking on a record button - not great as everyone then has to reconnect.
