### ISSUE TITLE
Token not found on live server

### ISSUE THREAD

**Issue by iarmankhan** [twilio/video-quickstart-js#79]
I'd uploaded quick start code on my dedicated live server which have node js + npm installed.
I'd also changed .env file's info with my own. Now, the site not showing option to create room and in console showing token not found.
The same code works nicely on localhost.
My site url :
[Video QuickStart](https://cipinterview.chaseinternationalpartners.com/video-quickstart-js/quickstart/public/)

**Comment by manjeshbhargav** [comment]
Hi @iarmankhan ,

Thank you for writing in with your question. It looks like you are running a separate web server to serve the web app. I'm getting a 404 error for the token endpoint, which means it is not visible to the client. Please take a look at the server code in the project to get an idea of how to deploy your quickstart application. Another option is to add a redirect rule in your web server to forward all requests to `/token` to the node process which serves tokens.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by iarmankhan** [comment]
I didn't change anything in the quickstart folder, I just changed the .env file information and it's working fine in my localhost. I first thought that this is node js version problem but I updated it to the latest on live server still no luck.
Can you guide me how to use quickstart example on live server?

**Comment by iarmankhan** [comment]
I checked the server file, there's a line 
`app.get('/token', function(request, response) `
Now I can't understand what this used for and how it gets the token.
Any help will be appreciated.
