### ISSUE TITLE
"Participant identity is invalid" error

### ISSUE THREAD

**Issue by dalalravi** [twilio/video-quickstart-js#8]
Hello,

I am wrapping up video-quickstart demo with my CI application but I am repetitively getting "Participant identity is invalid" error.

Can you please help me out with what I am doing wrong ?

Need help asap.

Many thanks.

**Comment by dalalravi** [comment]
![twilioerror](https://cloud.githubusercontent.com/assets/26052575/26140781/45bc5318-3af6-11e7-9a08-3bb93884b999.png)

**Comment by markandrus** [comment]
Hi @dalalravi, can you please share an example of the token you are generating? You may want to add a log statement to print it out.

**Comment by dalalravi** [comment]
Hello @markandrus ,

Many thanks for your reply.

I am generating and using access token using below given webservice which we are using for our apps too.

http://luvr.me/Luvr/Webservices/Webservice.php?Service=GetTwillioToken

I think if it was to be something wrong with token then it may have thrown "invalid access token" error.

Looking for your reply.

Thanks.

**Comment by markandrus** [comment]
Hi @dalalravi,

Thanks for sharing. I see the problem. I pasted one of your Access Tokens into https://jwt.io in order to decode it. The payload is below:

```json
{
  "jti": "SKde8dff81857eaf96e09212f90feb1e11-1495471470",
  "iss": "SKde8dff81857eaf96e09212f90feb1e11",
  "sub": "ACc7fb9741b3167e4694bdbc7ac7c3b3ff",
  "nbf": 1495471470,
  "exp": 1495475070,
  "grants": {
    "rtc": {
      "configuration_profile_sid": "VS2b0dfbb14558add4033f7d46030c84c7"
    }
  }
}
```

Some things to note:

* You appear to be generating an older form of Access Tokens (the grant `rtc` is deprecated; the new grant is `video`).
* Your Access Token is missing an `identity` grant, i.e. there is _no_ identity specified in the Access Token.

Can you please try using the method [here](https://github.com/twilio/video-quickstart-js/blob/e82dd696fcd209184135adb6100593cf07500da5/server/index.js#L44) for generating Access Tokens?

**Comment by GlobalvoicesGabriele** [comment]
Hi, 
I'm having a lot's of problem for understand how lunch the Quickstart, I'm receiving always the error (index.js:3 Uncaught ReferenceError: require is not defined
    at index.js:3)  in the row:  var Video = require('twilio-video');

I tried to fixing it including the require.js script (downloaded from quirejs.org) and using:

define(function (require) {
   var Video = require('twilio-video');
});

but I receive this error:
require.js:417 Uncaught Error: Mismatched anonymous define() module: function (require) {
var Video = require('twilio-video'); ...

Please someone could help me? What I should to do for execute the Quickstart script without errors?

Thank you so much

**Comment by GlobalvoicesGabriele** [comment]
Hi,
i tried to execute the code in windows but i'm receiving this error, could someone help me?
video-quickstart-js@1.0.0-dev start C:\xampp\htdocs\sacana\sitepoint\portal\doctors\call\video-quickstart-js-master
> npm run clean && npm run build && node server


> video-quickstart-js@1.0.0-dev clean C:\xampp\htdocs\sacana\sitepoint\portal\doctors\call\video-quickstart-js-master
> npm run clean:quickstart && npm run clean:examples


> video-quickstart-js@1.0.0-dev clean:quickstart C:\xampp\htdocs\sacana\sitepoint\portal\doctors\call\video-quickstart-js-master
> rimraf quickstart/public/index.js

'rimraf' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean:quickstart"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-quickstart-js@1.0.0-dev clean:quickstart: `rimraf quickstart/public/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-quickstart-js@1.0.0-dev clean:quickstart script 'rimraf quickstart/public/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the video-quickstart-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf quickstart/public/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs video-quickstart-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls video-quickstart-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\useradmin\AppData\Roaming\npm-cache\_logs\2017-05-30T12_59_23_882Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-quickstart-js@1.0.0-dev clean: `npm run clean:quickstart && npm run clean:examples`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-quickstart-js@1.0.0-dev clean script 'npm run clean:quickstart && npm run clean:examples'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the video-quickstart-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:quickstart && npm run clean:examples
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs video-quickstart-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls video-quickstart-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\useradmin\AppData\Roaming\npm-cache\_logs\2017-05-30T12_59_23_960Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-quickstart-js@1.0.0-dev start: `npm run clean && npm run build && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-quickstart-js@1.0.0-dev start script 'npm run clean && npm run build && node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the video-quickstart-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build && node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs video-quickstart-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls video-quickstart-js
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\useradmin\AppData\Roaming\npm-cache\_logs\2017-05-30T12_59_24_042Z-debug.log
