### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR - hosted on live server on port 3000

### ISSUE THREAD

**Issue by iarmankhan** [twilio/video-quickstart-js#82]
Hey, I successfully hosted this quickstart code on my live dedicated server on port 3000.
Now after `npm start` command it shows that app working on port 3000 but when I access it, it shows ERR_SSL_PROTOCOL_ERROR and without https I can't turn my camera on.
I'd talked with the server provider they said it's an application error. I can't find any solution on google.

**Comment by makarandp0** [comment]
Hello @iarmankhan,

most browsers allows applications access to local media ( `getUserMedia` ) only if they are hosted on secure (https) endpoints.  You can try workaround suggested by https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https
But eventually you would need to host your application on https endpoint.

**Comment by muratozenc** [comment]
Hello,

I have used Let's Encrypt to secure the connection. Now my site opens as https://mydomain.com, there is no problem but when I try to open https://mydomain.com:3000 I got the "ERR_SSL_PROTOCOL_ERROR" error. Where is the problem?
