### ISSUE TITLE
Record single party video

### ISSUE THREAD

**Issue by hwhelchel** [twilio/video-quickstart-js#83]
I read https://github.com/twilio/video-quickstart-js/issues/31 and https://github.com/twilio/video-quickstart-js/issues/75 but haven't been able to find a solution for my use case.

User should be able to:

1) Allow access to mic and camera. See themselves on camera before they start recording.
2) Click a button to start recording.
3) Click a button to stop recording.
4) Click a button to immediately play back the recording they just made.
5) Discard a recording and make a new one.

I've gotten 1) successfully accomplished using Twilio Video and the quick start guide. Now I'm unclear on how to proceed.

I imagine I need to just do all this work in the user's browser locally. I'm wondering if I should use WebRTC directly or if Twilio Video is doing some fallback polyfill magic for browsers that don't support WebRTC.

Most of the docs for Twilio highlight twilio video as a tool to enable multi party video calls and record them. Is my feature a good use case for twilio-video?

Thanks for your help in advance.

**Comment by manjeshbhargav** [comment]
Hi @hwhelchel ,

Thanks for trying out the Twilio Video JS SDK and writing in with your question. Right now, we enable you to [record individual media tracks](https://www.twilio.com/docs/video/api/recordings-resource) in a Group Room and use the [Compositions API](https://www.twilio.com/docs/video/api/compositions-resource) to combine them into a single Room recording.

For Peer-to-Peer Rooms, you can record media from MediaStreamTracks using the MediaRecorder API
as shown in [this example](https://webrtc.github.io/samples/src/content/getusermedia/record/).

I hope this helps with your use case.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by hwhelchel** [comment]
@manjeshbhargav thanks for your answer. I researched more yesterday and I think the simplest solution, since it's all happening locally on the user's browser, is just to use Media Streams and Media Tracks directly with the https://github.com/webrtcHacks/adapter
