### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by psiservices-bshet** [twilio/video-quickstart-js#85]
I get this error "Failed to load resource: the server responded with a status of 404 (Not Found)" when I change the frameRate from default to 5 using quickstart application

**Comment by makarandp0** [comment]
Thank you for reporting @psiservices-bshet, Can you provide some more details about the error - Which API/network request that results in 404 ? if you can look into network tab, and point to the resource in question, that would be useful. Also any code snippets ( or pointer to the line of code that you modified ) to reproduce the issue would help too.

Thanks,
Makarand
JSDK Team

**Comment by psiservices-bshet** [comment]
var connectOptions = {
        name: roomName,
        logLevel: 'debug',
         audio: { name: 'microphone-0' },
         video: { name: 'webcam-0',
                 frameRate: '5'} 
      };
I just added frameRate 5 and i get that error  "cannot get /favicon.ico " along with the error i mentioned. So I added <link rel="shortcut icon" href="#"> in my code. 

When I remove frameRate, the application works fine with default frameRate

**Comment by manjeshbhargav** [comment]
Hi @psiservices-bshet ,

The `frameRate` value must be a number, please try changing it to a number and let me know if that works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by psiservices-bshet** [comment]
I am joining multiple rooms within 10 seconds using single webcam at different framerate 1, 5, 10. When I do this I see it video works fine for 10 fps but not for 1fps and 5 fps, video gets stuck and I don't get any error I just see webcam feed is not sent at all.

**Comment by YDivya123** [comment]
when i try to play epub file from audio & Video getting error like HTTP load failed with status 404. Load of media resource https://app.flowoss.com/EPUB/audio/lesson1finalaudio01.mp3 failed.How to fix.It's a
 react js project.
