### ISSUE TITLE
Requested device not found - Unable to access Camera and Microphone

### ISSUE THREAD

**Issue by Kinza-Behram** [twilio/video-quickstart-js#86]
I am using the video-quickstart-js project. When I enter a room name and click on Join Room button, I am not able to join the room and get the following error msg in box at right of the screen

> Could not connect to Twilio: Requested device not found
> Unable to access Camera and Microphone

FYI I already copied the configuration parameters in .env before running project.
Is there a specific room name I am supposed to enter or setup? or am I missing any step? 

![image](https://user-images.githubusercontent.com/21155223/60256465-04fdf700-98eb-11e9-8f78-fdb6fc41db4e.png)

**Comment by manjeshbhargav** [comment]
Hi @Kinza-Behram ,

Thanks for writing in with your question. How are you accessing the quick start application? Are you using a `localhost` URL in your browser? If so, then it looks like the browser is not able to detect any camera and/or microphone on your system. Please let me know how you are accessing the quick start application.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Kinza-Behram** [comment]
Yes, I am using the localhost url http://localhost:3000 in chrome (version 75). The following are my browser settings for camera and microphone:
![image](https://user-images.githubusercontent.com/21155223/60500694-394f2a00-9cd4-11e9-8141-c90c4d48f3bc.png)

**Comment by jirachi155** [comment]
Having the exact same problem. Any news?

**Comment by manjeshbhargav** [comment]
Hi @jirachi155 , @Kinza-Behram ,

Can you try running this [WebRTC demo](https://github.com/webrtc/samples/tree/gh-pages/src/content/getusermedia/gum) app locally and see if that is able to successfully access your camera and microphone? I'm guessing that the browser is not able to detect your media devices for some reason.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by swanneptune** [comment]
I am also facing the same problem,can't access the media devices.

**Comment by gauravshrestha** [comment]
The video works for me on the "localvideosnapshot" page found in the examples section but I am facing the same problem on the quickstart screen:
![image](https://user-images.githubusercontent.com/11918176/65514183-71fd3a80-dea2-11e9-88bf-723747597756.png)

**Comment by makarandp0** [comment]
Hello @gauravshrestha, Thank you for reporting this issue. I am taking a look at this now.  Can you please share 
- OS and Browser versions that this issue repros on 
- Does camera work when using  https://webrtc.github.io/samples/src/content/getusermedia/gum/

Also one more thing useful  to try would be to use [ngrok](https://ngrok.com/) - to see if this issue has to do with accessing from localhost or something to do with http v/s https. 
  
Thanks,
Makarand 
JSDK Team

**Comment by jjstafford** [comment]
Hi @makarandp0 I'm having the exact same issue.  The link you provided above works fine (screenshot below) and all other examples of the quickstart work find (video filter, video snapshot, camera selection, etc).  The only thing that is broken is the quickstart page itself.  I cannot preview my camera OR create a room.  The behavior is exactly the same using HTTPS over ngrok or using localhost (I set the Chrome flag to treat localhost as secure).

When I try to create a room or preview camera, I get:
```> Unable to access Camera and Microphone

> Joining room 'Testroom'...
> Could not connect to Twilio: Permission denied by system```

![Screen Shot 2019-09-24 at 4 09 58 PM](https://user-images.githubusercontent.com/929003/65556980-8531f980-dee6-11e9-94dc-4038b4fa6424.png)
Room & camera preview test

![Screen Shot 2019-09-24 at 4 09 09 PM](https://user-images.githubusercontent.com/929003/65557004-9844c980-dee6-11e9-8531-763d36e27a20.png)
Result of https://webrtc.github.io/samples/src/content/getusermedia/gum/
(note camera partially obscured intentionally)

![Screen Shot 2019-09-24 at 4 10 29 PM](https://user-images.githubusercontent.com/929003/65557033-ae528a00-dee6-11e9-9790-da840b3627cf.png)
Local video snapshot test

![Screen Shot 2019-09-24 at 4 10 43 PM](https://user-images.githubusercontent.com/929003/65557044-b6122e80-dee6-11e9-8540-98cffaf077af.png)
Camera filter test

**Comment by jjstafford** [comment]
FWIW, the quickstart page actually does work fine on Firefox .  

![image](https://user-images.githubusercontent.com/929003/65557268-8f082c80-dee7-11e9-8518-bdf3d1ff262c.png)
Firefox / localhost (out of box ff config)

**Comment by makarandp0** [comment]
Thanks for the detailed information @jjstafford.  I am stumped, I have pretty much same config as yours and do not see repro. One quick check: what version is your macbook running on? Mine is MacOS Mojave - 10.14.6 (18G95)

Looking at the way we obtain local media tracks - from QuickStart app, there is nothing special about how it gets the local tracks. The only difference from the other apps that you mentioned  ( [localVideoFilter](https://github.com/twilio/video-quickstart-js/blob/836d777142f9076bc706f38907f2a3cc6b089fc9/examples/localvideosnapshot/src/helpers.js#L11) and [localVideoSnapShot](https://github.com/twilio/video-quickstart-js/blob/836d777142f9076bc706f38907f2a3cc6b089fc9/examples/localvideofilter/src/helpers.js#L15) is they do not try to get audio track. 

That makes me  wonder if somehow audio track permission are not available to quickstart app. Can you confirm that Chrome has permissions at "System Preferences => Security and Privacy => Microphone" ?

![Screen Shot 2019-09-24 at 5 32 14 PM](https://user-images.githubusercontent.com/6174737/65559881-53726000-def1-11e9-8723-bc49ae3c10c4.png)

If that is not the issue - I would  like to see what chrome://webrtc-internals/ has to say. Can you open that url on another tab, and then try to open quick start (and click on preview) again, and see if it shows  anything interesting about GetUserMedia requests call.

Thanks,
Makarand

**Comment by jjstafford** [comment]
@makarandp0 sure enough, the privacy preferences were the issue.  Thanks for that!   Now the next obvious question is, how can you detect that and handle more gracefully?  I would imagine there must be a way to still connect the video and create the room, even if the audio is blocked (bonus points for giving the user a hint as you just did here!)

**Comment by makarandp0** [comment]
This error definitely deserves some more messaging (maybe some extra logging when media permissions are denied by the OS) - but the error message in this case did say that "Permissions are denied by the System". I think at this point it's mostly up-to the app developers to decide how to surface the permissions issue to the user. I will check if API provides sufficiently granular  error code so that app developers can surface more meaningful message to the user.

**Comment by jjstafford** [comment]
@makarandp0 I think the only thing needing improvement is the error message.  Yes, it said "permission denied by system," but the full message was "**could not connect to Twilio** - permission denied..."  That sounds more like an API issue, which would presumably send a developer looking in the wrong direction.

**Comment by makarandp0** [comment]
@jjstafford - Yep, but I just want to clarify that the part 

> could not connect to Twilio

is generated by the [app](https://github.com/twilio/video-quickstart-js/blob/1.x/quickstart/src/index.js#L68) (quickstart) in this case. The real message returned by the API is:

> Permission denied by system 

So API is good, it's the app that needs to fix the messaging.
