### ISSUE TITLE
Not working in iPad safari 11+ & Android chrome 60+

### ISSUE THREAD

**Issue by babubalakrishnan** [twilio/video-quickstart-js#89]
Please suggest what changes needs to be made

**Comment by makarandp0** [comment]
Thank you for writing with your issue @babubalakrishnan. I will verify and get back to you. In the meanwhile have you tried https://github.com/twilio/video-quickstart-js/tree/1.x/examples/mediadevices 
sample - I made some changes to it couple weeks back, and had verified then that it worked on mobile devices. Let me know if that sample works for you.

Thanks, 
Makarand

**Comment by makarandp0** [comment]
@babubalakrishnan - I am closing this old issue. Let us know if you have any issues with https://github.com/twilio/video-quickstart-js/tree/master/examples/mediadevices
