### ISSUE TITLE
Camera remains active following leaving room

### ISSUE THREAD

**Issue by newtriks** [twilio/video-quickstart-js#9]
**Current behaviour:**

1. Follow the readme steps
2. Preview camera
    - green light displayed on computer
    - camera preview loads in browser
3. Enter a room name
4. Join room
5. Leave room
    - green light _displayed_ on computer
    - camera preview unloads in browser

**Expected behaviour:**

5. Leave room
  - green light _no longer displays_ on computer
  - camera preview unloads in browser

`video-quickstart-js version: 1.0.0-dev`

**Comment by markandrus** [comment]
Thanks for the report—I can reproduce (although I am surprised you have 1.0.0-dev; shouldn't this be 1.0.0?). Will fix shortly.

**Comment by newtriks** [comment]
@markandrus no worries. In regards to version, I was referring to the version of this library which shows as https://github.com/twilio/video-quickstart-js/blob/master/package.json#L3.
