### ISSUE TITLE
Works on Desktop, but not in Chrome on Android or Safari on iOS

### ISSUE THREAD

**Issue by mark0978** [twilio/video-quickstart-js#97]
More details can be found here, but the gist is in the title.

https://stackoverflow.com/questions/59113357/why-does-twilio-video-fail-on-chrome-and-safari-on-ipad-and-android

I'm using the JS quickstart for video that has the code located here https://github.com/twilio/video-quickstart-js . The rest of the app works, but trying to preview the video gives a failure on all the mobile platforms.

The example at https://mdn-samples.mozilla.org/s/webrtc-capturestill/ works as expected in Chrome on Android and Safari on iOS, so this looks like it has to be a Twilio bug.

The error is "Unable to access Camera and Microphone" which is coming from here:

```
// Preview LocalParticipant's Tracks.
document.getElementById('button-preview').onclick = function() {
  var localTracksPromise = previewTracks
    ? Promise.resolve(previewTracks)
    : Video.createLocalTracks();

  localTracksPromise.then(function(tracks) {
    window.previewTracks = previewTracks = tracks;
    var previewContainer = document.getElementById('local-media');
    if (!previewContainer.querySelector('video')) {
      attachTracks(tracks, previewContainer);
    }
  }, function(error) {
    console.error('Unable to access local media', error);
    log('Unable to access Camera and Microphone');
  });
};
```

**Comment by mark0978** [comment]
Also tried it with `    "twilio-video": "2.0.0-beta15"` and while it takes longer, it still fails.  It never prompts for permission to use the camera either if that helps.

**Comment by makarandp0** [comment]
Hello @mark0978, Thank you for writing about this issue.

These samples should work on mobile devices. They works fine on my iPad (13.1.3)
Couple of things to verify:
1. How are you accessing the quick-start from mobile devices? Are you using it from `http` or `https` endpoint? media permissions do require  secure endpoint.
2. Please check if the camera / microphone permissions are not denied for the endpoint you are accessing from.  Settings -> Safari -> Settings for WebSites ->Camera/Microphone

Also please checkout https://github.com/twilio/video-quickstart-js/blob/master/examples/mediadevices/src/helpers.js 
This sample better demonstrates accessing media on mobile devices.

Let me know If this helps, 
Thanks,
Makarand
JSDK Team

**Comment by amebrahimi** [comment]
@mark0978  Hello, Is your server on https or Http? if it is on Http this is the solution. https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https

**Comment by manjeshbhargav** [comment]
@mark0978 ,

I'm going to close this issue now. Please feel free to reopen if the above suggestions do not help you out or you need further clarifications.

Thanks,

Manjesh Malavalli
JSDK Team
